<?php
declare(strict_types=1);
namespace App\Services;
use App\Support\Database;
final class DepositService {
 public function __construct(private ?Database $db,private WalletService $wallets,private DynamicFormService $forms,private NotificationService $notifications){}
 public function methods(int $countryId):array{return $this->db?->select('SELECT m.* FROM deposit_methods m JOIN deposit_method_countries c ON c.deposit_method_id=m.id WHERE c.country_id=? AND m.enabled=1 ORDER BY m.sort_order,m.name',[$countryId])??[];}
 public function method(int $countryId,int $methodId):?array{return $this->db?->one('SELECT m.* FROM deposit_methods m JOIN deposit_method_countries c ON c.deposit_method_id=m.id WHERE m.id=? AND c.country_id=? AND m.enabled=1',[$methodId,$countryId]);}
 public function quote(array $country,int $methodId,int $amount):array{$method=$this->method((int)$country['id'],$methodId);if(!$method)throw new \RuntimeException('Deposit method is unavailable for your Country Pack.');if($amount<(int)$method['minimum_amount_minor']||($method['maximum_amount_minor']!==null&&$amount>(int)$method['maximum_amount_minor']))throw new \InvalidArgumentException('Amount is outside the method limits.');$fee=$this->fee($amount,$method);return ['method'=>$method,'fee_minor'=>$fee,'expected_credit_minor'=>$method['fee_behavior']==='DEDUCT_FROM_CREDIT'?$amount-$fee:$amount];}
 public function submit(array $user,array $country,int $methodId,int $amount,array $values,array $files=[]):array{if(!$this->db)throw new \RuntimeException('Database unavailable.');$quote=$this->quote($country,$methodId,$amount);$method=$quote['method'];$definition=$this->forms->definition($method['form_id']?(int)$method['form_id']:null);$this->forms->validate($definition,$values,$files);$wallet=$this->wallets->walletFor($user,$country);$ref='DEP-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(6)));$result=$this->db->transaction(function(Database $db)use($user,$country,$method,$wallet,$amount,$quote,$values,$definition,$ref){$snapshot=$this->forms->snapshot($method['form_id']?(int)$method['form_id']:null,'DEPOSIT');$db->execute('INSERT INTO deposit_requests(public_id,reference,user_id,wallet_id,country_id,currency_code,deposit_method_id,form_snapshot_id,method_snapshot,requested_amount_minor,fee_minor,expected_credit_minor) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[bin2hex(random_bytes(16)),$ref,$user['id'],$wallet['id'],$country['id'],$country['currency_code'],$method['id'],$snapshot,json_encode(['name'=>$method['name'],'instructions'=>$method['instructions'],'fee_type'=>$method['fee_type'],'fee_value'=>$method['fee_value'],'fee_behavior'=>$method['fee_behavior']],JSON_THROW_ON_ERROR),$amount,$quote['fee_minor'],$quote['expected_credit_minor']]);$id=(int)$db->pdo()->lastInsertId();foreach($values as$key=>$value){$field=array_values(array_filter($definition,fn($f)=>$f['field_key']===$key))[0]??null;if($field&&$field['field_type']!=='FILE')$db->execute('INSERT INTO deposit_submission_values(deposit_request_id,field_key,field_label,value_text) VALUES (?,?,?,?)',[$id,$key,$field['label'],is_array($value)?implode(',',array_map('strval',$value)):(string)$value]);}return ['id'=>$id,'reference'=>$ref];});$this->notifications->create((int)$user['id'],'deposit_submitted','Deposit request submitted','Your deposit request is awaiting review.',['url'=>'/dashboard/deposit/'.$result['reference']]);return $result;}
 public function approve(int $depositId,int $adminId,string $note=''):array{if(!$this->db)throw new \RuntimeException('Database unavailable.');$result=$this->db->transaction(function(Database $db)use($depositId,$adminId,$note){$d=$db->lockForUpdate('SELECT * FROM deposit_requests WHERE id=?',[$depositId]);if(!$d)throw new \RuntimeException('Deposit not found.');if($d['status']==='APPROVED'&&$d['approved_ledger_transaction_id'])return ['idempotent'=>true,'ledger_id'=>$d['approved_ledger_transaction_id'],'user_id'=>$d['user_id']];if(!in_array($d['status'],['PENDING','UNDER_REVIEW'],true))throw new \RuntimeException('Deposit is not eligible for approval.');$ledger=$this->wallets->move((int)$d['wallet_id'],'DEPOSIT','CREDIT',(int)$d['expected_credit_minor'],'Approved manual deposit','deposit',(string)$d['id'],$adminId,$note);$db->execute('UPDATE deposit_requests SET status="APPROVED",reviewed_at=NOW(),reviewed_by_user_id=?,admin_notes=?,approved_ledger_transaction_id=?,updated_at=NOW() WHERE id=?',[$adminId,$note,$ledger['id'],$depositId]);return $ledger+['user_id'=>$d['user_id']];});$this->notifications->create((int)$result['user_id'],'deposit_approved','Deposit approved','Your wallet has been credited.',['url'=>'/dashboard/deposit/'.$depositId]);return $result;}
 public function review(int $id,int $adminId):void{$this->db?->execute('UPDATE deposit_requests SET status="UNDER_REVIEW",reviewed_at=NOW(),reviewed_by_user_id=?,updated_at=NOW() WHERE id=? AND status="PENDING"',[$adminId,$id]);}
 public function reject(int $id,int $adminId,string $reason):void{if(trim($reason)==='')throw new \InvalidArgumentException('A rejection reason is required.');$deposit=$this->db?->one('SELECT user_id FROM deposit_requests WHERE id=?',[$id]);$this->db?->execute('UPDATE deposit_requests SET status="REJECTED",rejection_reason=?,reviewed_at=NOW(),reviewed_by_user_id=?,updated_at=NOW() WHERE id=? AND status IN ("PENDING","UNDER_REVIEW")',[$reason,$adminId,$id]);if($deposit)$this->notifications->create((int)$deposit['user_id'],'deposit_rejected','Deposit rejected',$reason,['url'=>'/dashboard/deposit/'.$id]);}
 public function forUser(int $userId,int $page=1,int $perPage=20):array{if(!$this->db)return ['items'=>[],'total'=>0];$total=(int)$this->db->scalar('SELECT COUNT(*) FROM deposit_requests WHERE user_id=?',[$userId]);return ['items'=>$this->db->select('SELECT d.*,m.name method_name FROM deposit_requests d JOIN deposit_methods m ON m.id=d.deposit_method_id WHERE d.user_id=? ORDER BY d.submitted_at DESC LIMIT ?,?',[$userId,max(0,($page-1)*$perPage),$perPage]),'total'=>$total];}
 public function attachFiles(int $depositId,array $files):void{if(!$this->db)return;foreach($files as$key=>$file){if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)continue;$mime=(new \finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']);$path=app('upload')->store($file,true,false);$this->db->execute('INSERT INTO deposit_files(deposit_request_id,field_key,storage_path,original_filename,mime_type,file_size) VALUES (?,?,?,?,?,?)',[$depositId,(string)$key,$path,basename((string)$file['name']),$mime,(int)$file['size']]);}}
 public function cancel(int $userId,string $reference):void{$count=$this->db?->execute('UPDATE deposit_requests SET status="CANCELLED",cancelled_at=NOW(),updated_at=NOW() WHERE user_id=? AND reference=? AND status="PENDING"',[$userId,$reference])??0;if(!$count)throw new \RuntimeException('This deposit can no longer be cancelled.');}
 public function findForUser(int $userId,string $reference):?array{return $this->db?->one('SELECT d.*,m.name method_name FROM deposit_requests d JOIN deposit_methods m ON m.id=d.deposit_method_id WHERE d.user_id=? AND d.reference=?',[$userId,$reference]);}
 public function values(int $id):array{return $this->db?->select('SELECT * FROM deposit_submission_values WHERE deposit_request_id=?',[$id])??[];}
 public function queue(array $filters=[],int $page=1):array{if(!$this->db)return ['items'=>[],'total'=>0];$where=['1=1'];$params=[];foreach(['status'=>'d.status','country_id'=>'d.country_id','method_id'=>'d.deposit_method_id'] as $k=>$col)if(($filters[$k]??'')!==''){$where[]=$col.'=?';$params[]=$filters[$k];}if(($filters['q']??'')!==''){$where[]='(d.reference LIKE ? OR u.email LIKE ?)';$params[]='%'.$filters['q'].'%';$params[]='%'.$filters['q'].'%';}$sql=implode(' AND ',$where);$total=(int)$this->db->scalar('SELECT COUNT(*) FROM deposit_requests d JOIN users u ON u.id=d.user_id WHERE '.$sql,$params);$params[]=max(0,($page-1)*20);return ['items'=>$this->db->select('SELECT d.*,u.email,u.first_name,u.last_name,m.name method_name FROM deposit_requests d JOIN users u ON u.id=d.user_id JOIN deposit_methods m ON m.id=d.deposit_method_id WHERE '.$sql.' ORDER BY d.submitted_at DESC LIMIT ?,20',$params),'total'=>$total];}
 private function fee(int $amount,array $m):int{if($m['fee_type']==='NONE')return 0;if($m['fee_type']==='FIXED')return (int)$m['fee_value'];[$a,$b]=array_pad(explode('.',(string)$m['fee_value'],2),2,'');$bp=(int)$a*100+(int)str_pad(substr($b,0,2),2,'0');return intdiv($amount*$bp,10000);}
}
