<?php
declare(strict_types=1);

namespace App\Services;

final class HomepageExperienceService
{
    public function forCountry(array $country, string $language = 'en'): array
    {
        $code = strtoupper((string)($country['code'] ?? ''));
        $key = $code !== '' ? $code : 'GLOBAL';
        $profiles = $this->profiles();
        $profile = $profiles[$key] ?? $profiles['GLOBAL'];
        $profile['country_name'] = (string)($country['name'] ?? '');
        $profile['currency_code'] = (string)($country['currency_code'] ?? 'USD');
        $profile['currency_symbol'] = (string)($country['currency_symbol'] ?? '$');
        $profile['language'] = $language;
        $profile['security_points'] = $this->securityPoints($profile['variant']);
        $profile['process'] = $this->process($profile['variant']);
        $profile['resources'] = $this->resources($profile['variant']);
        $profile['faq'] = $this->faq($profile, $country);
        return $profile;
    }

    private function profiles(): array
    {
        return [
            'US' => $this->profile('institutional','Investing, made easier to examine.','Build a portfolio around opportunities you understand.','Review the company, offering terms, projected return, duration and supporting information before deciding where your capital goes.','A clearer way to approach private investment opportunities','Good investing starts with understanding what you are buying. We organise each opportunity around the facts that matter: the business, the terms, the time horizon and the information available to support your decision.','Designed for deliberate portfolio building','Move from discovery to decision with a consistent view of price, duration, projected outcome and company information—without burying the important details.','Research before commitment','Every opportunity should earn a place in your portfolio. We give company context and offering terms enough room to be read, compared and questioned before you invest.','Put your next investment decision on firmer ground.','Create your account, review the opportunities currently available to you and invest only when the terms make sense.'),
            'GB' => $this->profile('editorial','A considered approach to investing.','Opportunity, context and terms in one place.','Explore investments with the company information, commercial context and offering details needed to make a more informed decision.','Investment decisions deserve more than a headline','We present opportunities with a measured editorial approach: what the business does, how the investment is structured, what the projected outcome means and which details deserve closer attention.','Clarity without unnecessary noise','The experience is intentionally calm and information-led, making it easier to compare opportunities without turning the decision into a stream of promotional claims.','Read the business, then the offer','We believe the quality of an investment decision improves when the company story and the actual investment terms are examined separately and then considered together.','Make room for a better-informed decision.','Explore opportunities, review the supporting information and build your portfolio at a pace that suits you.'),
            'DE' => $this->profile('structured','Investments with structure and transparency.','Understand the terms before you commit capital.','A disciplined investment experience built around clear company information, explicit offering terms and traceable account activity.','Structure turns information into something useful','Each opportunity is broken down into practical decision points: business profile, investment price, projected return, duration and availability. The aim is to make comparison straightforward.','Built for careful evaluation','Clear records, consistent presentation and visible transaction history help you understand both the opportunity and what happens after you invest.','A process you can inspect','Investment decisions should be repeatable, not improvised. Our approach gives every opportunity the same core evaluation framework while preserving the facts that make each business different.','Invest with a process you can explain.','Review the information, compare the terms and proceed only when the opportunity fits your own objectives.'),
            'FR' => $this->profile('editorial','Give every investment decision more context.','Discover opportunities without losing sight of the underlying business.','Company fundamentals and investment terms are presented side by side so you can evaluate an opportunity as a whole, not as a single projected number.','Investing begins with perspective','An opportunity is more than a return figure. We give space to the company, its activity, the structure of the offer and the practical details that shape the investment experience.','Information designed to be read','The platform favours clear explanations, deliberate pacing and transparent account records over compressed promotional messaging.','Understand before you allocate','Our investment philosophy is simple: begin with the business, understand the structure, consider the time horizon and only then decide whether the opportunity belongs in your portfolio.','Turn interest into an informed decision.','Open your account and explore the opportunities currently available with the detail they deserve.'),
            'IT' => $this->profile('editorial','Invest with a stronger understanding of the opportunity.','From company story to investment terms, see the full picture.','Explore opportunities through a richer view of the business, the price, the duration and the projected outcome before you make a commitment.','The company matters as much as the offer','We build the investment experience around context. That means understanding the business first, then reading the investment terms with a clearer idea of what sits behind them.','A more thoughtful investment journey','Company information, offering details and account activity are kept clear and connected so that every step remains understandable.','Choose with context','We believe investors make stronger decisions when information is presented as a coherent story rather than a collection of isolated numbers.','Start with understanding. Build from there.','Review the opportunities available to you and create a portfolio shaped by informed choices.'),
            'ES' => $this->profile('warm','Make investing feel more understandable.','Clear opportunities, practical information and a straightforward path from discovery to portfolio.','See what a company does, how the investment is structured and what the projected outcome means before deciding whether to invest.','A simpler way to understand an opportunity','We remove unnecessary friction from the research process by bringing company information and offering terms into one clear experience.','Confidence comes from knowing what you are doing','Clear terms, visible account records and simple portfolio tracking help you stay connected to every investment decision you make.','Invest with purpose, not pressure','Take the time to understand the business and the terms. The platform is designed to support a deliberate decision rather than rush you toward one.','Explore your next opportunity with clarity.','Create an account, review what is available and move forward when the investment fits your objectives.'),
            'NL' => $this->profile('modern','Clear information. Better investment decisions.','A modern way to discover, compare and track investment opportunities.','See the business, the terms and the projected outcome in a clean experience designed to make comparison easier.','Less friction between research and action','We organise investment information around the questions investors actually need answered, then keep the account experience equally clear after a decision is made.','Built to keep the important details visible','Offering price, duration, projected return and company information remain easy to find instead of disappearing behind layers of interface.','Compare on substance','A useful platform should make differences easier to see. We present opportunities consistently so you can compare the terms without flattening the businesses behind them.','Make your next decision easier to understand.','Explore available investments and build your portfolio with a clearer view of every step.'),
            'CH' => $this->profile('precision','Precision matters when capital is at work.','Review investment opportunities through clear terms, disciplined presentation and transparent records.','A focused investment experience that separates company facts from platform offering terms and keeps both visible throughout your decision.','Details should remain details','We avoid blurring company information with projected investment outcomes. Each has its own place, making the opportunity easier to examine with precision.','A platform designed around control','Structured records, clear transaction history and deliberate security controls give you a more orderly way to manage the investment process.','Discipline before allocation','We favour careful review over urgency: understand the company, inspect the offering terms, consider the duration and decide from there.','Approach your next investment with precision.','Review current opportunities and proceed when the facts and terms meet your own standard.'),
            'SE' => $this->profile('minimal','Investing with fewer distractions.','Only the information you need to understand an opportunity and make your own decision.','A clean investment experience centred on company context, transparent terms and simple portfolio visibility.','Clarity is a design choice','We keep the experience intentionally focused so the important parts of an opportunity remain easy to find and easy to compare.','Simple does not mean shallow','Behind the restrained interface are the details that matter: price, duration, projected outcome, company information and transaction records.','Make space for judgement','The platform gives you information and structure without trying to manufacture urgency. The final decision remains yours.','A calmer way to build your portfolio.','Explore opportunities with the time and information needed to make a deliberate choice.'),
            'NO' => $this->profile('minimal','A straightforward way to evaluate investments.','Clear company information, visible terms and portfolio tracking without unnecessary complexity.','Review the opportunity in full before you decide: the business, the price, the duration and the projected outcome.','Keep the decision understandable','Investment information is organised in a consistent, readable way so you can spend more time evaluating and less time searching for the terms.','Transparency throughout the journey','From the first opportunity page to your transaction history, important account and investment information stays visible.','Think long enough to understand it','We prefer deliberate decisions to rushed ones. Read the company, examine the offer and decide whether it fits your own plan.','Build with clarity, one decision at a time.','See what is currently available and invest when you are satisfied with the information in front of you.'),
            'DK' => $this->profile('minimal','Invest with a clear view of the essentials.','Opportunities presented with practical information, transparent terms and a clean account experience.','Understand what you are investing in, how the offer works and what the projected outcome represents before you proceed.','The important information should be easy to find','We reduce visual and informational clutter so company context and offering terms can do the work.','Designed around visibility','Your investments, maturity dates, transactions and account activity remain organised in one place after you commit.','Good decisions do not need noise','We present the information; you decide whether the opportunity deserves your capital.','See the opportunity clearly before you act.','Open your account and explore investments through a simpler, more deliberate experience.'),
            'CA' => $this->profile('editorial','Build your portfolio with more context.','Explore investment opportunities with the business story and the offering terms kept equally visible.','Review company information, investment pricing, projected return and duration in a single decision-friendly experience.','Context makes comparison more useful','A list of numbers can tell you what an offer says; company context helps you understand what the investment is connected to. We bring both together.','Clarity from discovery to portfolio','The same emphasis on understandable information continues through your account, transaction history and investment tracking.','Look beyond a single metric','Projected return is one part of an opportunity. We encourage a broader view that also considers the business, structure and time horizon.','Build a portfolio you understand.','Explore the opportunities available to you and make each allocation with a clearer view of the details.'),
            'BR' => $this->profile('vibrant','Turn opportunity into an informed investment decision.','Discover businesses, understand the offer and track your investments from one clear platform.','A more direct way to move from curiosity to research, from research to decision and from decision to portfolio.','Opportunity becomes useful when the terms are clear','We make the investment structure visible alongside the company information so you can understand what you are considering before you commit.','Built for active investors who still value detail','A faster experience does not have to mean a shallow one. Price, projected return, duration and company context remain part of the decision.','Energy with discipline','Explore widely, compare carefully and invest selectively. The platform is built to make that process easier to repeat.','Find the opportunity that earns your attention.','Create your account, explore available investments and build your portfolio with greater clarity.'),
            'MX' => $this->profile('warm','Invest with clarity from the first look.','Understand the company, the offer and the timeline before making your decision.','A practical investment experience that brings together the information you need to evaluate opportunities with greater confidence.','Start with the questions that matter','What does the company do? What are the terms? How long is the investment? What does the projected outcome mean? We structure each opportunity around those questions.','A clearer path from research to portfolio','Once you invest, your account keeps the activity visible through organised transactions, investment records and maturity information.','Know why you are investing','The platform is designed to support decisions based on information and fit, not pressure or hype.','Take the next step with a clearer picture.','Explore current opportunities and invest only after the company and the terms make sense to you.'),
            'JP' => $this->profile('minimal','Clarity before commitment.','A restrained investment experience focused on the information that matters.','Company context, offering terms and account records are presented with precision so you can evaluate each opportunity without distraction.','A quiet interface for an important decision','We use structure and restraint to keep the company, price, duration and projected result easy to understand.','Order throughout the investment process','From discovery to portfolio tracking, each stage is organised so the information remains consistent and readable.','Examine first, decide second','The platform supports careful consideration. It does not replace your judgement or turn projected outcomes into promises.','Choose with a clear understanding of the terms.','Review the opportunities available to you and proceed when the information supports your decision.'),
            'KR' => $this->profile('modern','A sharper way to explore investment opportunities.','Company insight, offering terms and portfolio visibility in one modern experience.','Move quickly through the information without losing the details that matter to an investment decision.','Designed for fast understanding, not rushed decisions','A clean structure helps you identify the company, price, projected return, duration and availability at a glance, then go deeper when needed.','Modern infrastructure, visible records','Account activity, transactions and investment positions remain organised so you can follow what happens after each decision.','Speed should improve research, not replace it','Use the platform to understand and compare opportunities more efficiently while keeping the final decision deliberate.','Explore faster. Decide carefully.','Open your account and review the investments currently available with a clearer view of the terms.'),
            'SG' => $this->profile('precision','Investment opportunities, presented with discipline.','Evaluate companies and offering terms through a clean, structured investment experience.','A focused platform for reviewing the business, price, projected return, duration and supporting information before allocating capital.','Built around decision-quality information','Every opportunity is organised to separate verified company facts from platform-configured investment terms, helping you understand exactly what each piece of information represents.','Operational clarity from start to finish','The same structured approach extends to transactions, portfolio records, maturity information and account security.','Treat every allocation as a decision process','Review the company, inspect the terms, consider the time horizon and make your decision without relying on a single projected figure.','Put structure behind your next investment decision.','Explore current opportunities and build your portfolio through a disciplined, transparent process.'),
            'HK' => $this->profile('premium','A more refined way to evaluate opportunity.','Discover investments through a polished experience that keeps important commercial details in view.','Company information, offering terms and portfolio visibility come together in an experience designed for deliberate capital allocation.','Refinement should improve understanding','A premium experience is not about decoration. It is about presenting the business, the investment structure and the account journey with enough clarity to support judgement.','Control without unnecessary complexity','From security to transaction records, the platform is designed to keep your investment activity organised and accessible.','Selectivity over volume','We believe investors benefit from examining fewer opportunities more carefully rather than treating every listing as interchangeable.','Consider the opportunity. Understand the terms. Decide.','Create your account and explore investments with a more focused view of what matters.'),
            'IN' => $this->profile('vibrant','Discover opportunities with the details in view.','A dynamic investment experience built around company context, transparent terms and simple portfolio tracking.','Explore opportunities efficiently while still understanding the price, projected return, duration and business behind each investment.','More information should create more clarity','We organise the key details into a practical decision flow so you can move from discovery to deeper research without losing context.','Built for momentum with control','The experience is responsive and direct, while transaction records, investment positions and maturity information remain clearly organised.','Explore widely, choose carefully','Access to opportunity is useful only when paired with a disciplined way to evaluate it. We make the research process easier to repeat.','Your next opportunity should make sense before it gets your capital.','Explore what is available, compare the terms and build your portfolio through informed choices.'),
            'AU' => $this->profile('modern','A clearer way to find your next investment opportunity.','Explore businesses, compare terms and keep your portfolio organised in one straightforward experience.','We bring the company story and the investment structure together so you can understand what is being offered before you commit.','Make the research practical','Important details should not require detective work. Company context, price, duration and projected outcome are organised for quick understanding and deeper review.','Straightforward from account to portfolio','The platform keeps your transactions, investment positions and maturity details visible after you invest.','Practical investing starts with a practical process','Understand the opportunity, compare it with your own objectives and make the decision on your terms.','Explore what is available with a clearer view.','Create an account and start reviewing opportunities through a simple, information-led process.'),
            'NZ' => $this->profile('editorial','Take a measured approach to new investment opportunities.','Understand the business and the offer before deciding where your capital belongs.','A calm, information-led platform for exploring companies, reviewing investment terms and tracking your portfolio.','Good decisions benefit from a little space','We give company context and offering details enough room to be understood rather than compressing the opportunity into a promotional headline.','A simple experience with meaningful detail','The platform remains easy to navigate while preserving the information needed to examine an opportunity properly.','Measure twice, invest once','Read the company information, understand the terms and decide only when the opportunity fits your own goals and tolerance for risk.','Build your portfolio at a considered pace.','Explore available investments and move forward when the information gives you enough reason to do so.'),
            'ZA' => $this->profile('modern','Put clearer information behind every investment decision.','Explore opportunities, understand the terms and keep your portfolio activity visible.','A practical investment experience centred on company context, transparent offering details and organised account records.','Information should help you decide, not overwhelm you','We structure each opportunity around the essentials and make deeper company information available when you want to go further.','Built for visibility and control','Your investment positions, transactions and maturity information remain accessible so the account experience stays understandable after you invest.','Opportunity needs discipline','Review widely, compare carefully and decide based on the fit between the investment and your own objectives.','Start with the details. Decide from there.','Create your account and explore the opportunities currently available with a clearer view of the terms.'),
            'AE' => $this->profile('premium','Capital deserves a more considered experience.','Explore investment opportunities through a refined platform built around clarity, control and informed decision-making.','Review the company, structure, projected outcome and duration in an experience designed to keep important details visible.','A premium experience should make decisions clearer','We combine polished presentation with disciplined information architecture so the investment remains the focus, not the interface.','Control at every stage','Account security, transaction records and portfolio visibility are treated as core parts of the investment experience.','Select opportunities with intention','We favour a measured process: understand the company, examine the terms, consider the time horizon and decide when the opportunity meets your standard.','Approach your next allocation with greater clarity.','Open your account and explore opportunities through a more refined, information-led experience.'),
            'SA' => $this->profile('premium','A disciplined approach to investment opportunity.','Clarity, structure and account control for every stage of the investment journey.','Evaluate the business, the offering terms and the projected outcome through a platform designed for deliberate capital decisions.','Built around informed allocation','We present each opportunity with enough context to understand both the company and the investment structure before you proceed.','Confidence through clear records and controls','Your account experience keeps investment positions, transactions and maturity details organised while security controls protect access.','Patience is part of the process','An opportunity should be understood before it is funded. We support a measured review of the company, terms and time horizon.','Invest when the information meets your standard.','Create your account and review the opportunities currently available with a clear view of the terms.'),
            'PL' => $this->profile('structured','Bring more structure to investment decisions.','A clear framework for reviewing companies, offering terms and portfolio activity.','Understand the opportunity through consistent information: business profile, investment price, projected return, duration and availability.','A repeatable process makes comparison easier','We organise every opportunity around the same core decision points so you can compare investments without losing the details that make each company distinct.','Structure continues after you invest','Transactions, positions and maturity information stay organised in your account, making it easier to follow what has happened and what comes next.','Use a framework, not a feeling','Review the business, inspect the terms and decide whether the opportunity fits your plan before allocating capital.','Give your next investment decision a clearer structure.','Explore the opportunities available to you and proceed when the information supports your choice.'),
            'AT' => $this->profile('precision','Invest with a more precise view of the opportunity.','Company facts, investment terms and account records presented with deliberate clarity.','A focused experience for examining price, projected outcome, duration and the business behind the offer.','Precision begins with separation','Company information and investment terms are related, but they are not the same thing. We present them clearly so you can evaluate each on its own merits.','Designed for orderly decision-making','Consistent presentation and visible records make it easier to understand both the opportunity and your activity after investing.','Careful review before commitment','Take the time to understand the business and the structure of the offer before deciding whether it belongs in your portfolio.','Make the decision only after the details are clear.','Review current opportunities and invest when the terms align with your own objectives.'),
            'BE' => $this->profile('editorial','See the investment in its wider context.','Company information and offering terms brought together for a more complete decision.','Explore opportunities through a balanced view of the business, the structure, the projected outcome and the time horizon.','An investment is a story and a set of terms','The business explains what sits behind the opportunity; the offering explains how the investment works. Both deserve to be understood.','A platform built for readable information','We favour clear explanations and organised records so the investment journey remains understandable from research through portfolio tracking.','Context before conclusion','Look at the company, then the offer, then how the two fit your objectives. A projected figure should never do all the thinking for you.','Give your next opportunity the attention it deserves.','Create your account and explore investments with the context needed to make your own decision.'),
            'IE' => $this->profile('editorial','A straightforward place to understand investment opportunities.','Explore businesses, read the terms and make decisions without unnecessary complexity.','We bring together company context, investment structure and portfolio visibility in an experience designed to stay understandable.','Start with what you are actually investing in','We lead with the business and its context, then make the offering price, projected return and duration easy to review.','Clear before and after the investment','The same straightforward approach continues in your account through transactions, positions and maturity information.','A decision should still feel like yours','We provide information and structure. You decide whether the opportunity fits your goals and risk tolerance.','Explore with curiosity. Invest with understanding.','Open your account and review the opportunities currently available to you.'),
            'PH' => $this->profile('vibrant','Discover companies. Understand the offer. Invest with clarity.','A more engaging way to explore opportunities while keeping the important details in view.','See the business, investment price, projected return and duration together before deciding whether to add an opportunity to your portfolio.','Make every opportunity easier to understand','We organise the research journey so you can move from a quick overview to the details without losing the context behind the investment.','Built for progress with visibility','Once you invest, your account keeps transactions, positions and maturity information organised and easy to follow.','Be open to opportunity, selective with capital','Explore what is available, compare the terms and choose only the investments that make sense for your own objectives.','See what deserves a place in your portfolio.','Create your account and start exploring the opportunities currently available.'),
            'TT' => $this->profile('warm','A clearer path from opportunity to investment.','Understand the company, the terms and the timeline before you commit.','A practical platform for exploring investment opportunities with the information needed to make a deliberate decision.','Keep the investment conversation grounded','Company context and offering terms are presented together so you can look beyond a headline return and understand the structure of the opportunity.','Designed to stay understandable','Your account keeps transactions, positions and maturity information organised after you invest.','Take opportunity seriously','Review the business, inspect the terms and decide whether the investment fits your own plan rather than reacting to urgency.','Start with understanding, then decide.','Explore the opportunities available to you and invest when the details make sense.'),
            'JM' => $this->profile('vibrant','Opportunity looks better when the details are clear.','Explore investments with company context, visible terms and straightforward portfolio tracking.','A direct, engaging investment experience that keeps price, projected return, duration and business information easy to understand.','Move from interest to understanding','We make it simple to go beyond the headline and see how the opportunity is structured before you decide.','Your portfolio should stay easy to follow','Transactions, investment positions and maturity information remain organised in your account so you can see where things stand.','Stay open, stay selective','Explore opportunities confidently, but let the business and the terms—not momentum—determine whether you invest.','Find the opportunity that makes sense to you.','Open your account and review what is currently available with a clearer view of the details.'),
            'BB' => $this->profile('warm','Invest with a calm, clear view of the opportunity.','Company information, transparent terms and portfolio visibility in one straightforward experience.','Take the time to understand the business, the price, the projected outcome and the duration before making your decision.','A better decision starts with a better view','We bring the main parts of an opportunity together so you can understand the investment without jumping between disconnected information.','Simple to use, serious about the details','The platform keeps the experience approachable while preserving the terms and records that matter.','Let clarity set the pace','There is no need to rush an investment decision. Review the information and proceed only when the opportunity fits your goals.','Build your portfolio with a clearer perspective.','Explore available opportunities and invest when you are comfortable with the company and the terms.'),
            'GLOBAL' => $this->profile('institutional','Invest with greater clarity.','Understand the opportunity before you commit capital.','Discover carefully presented investment opportunities with company information, offering terms, projected outcomes and portfolio tracking in one place.','A stronger investment decision starts with context','We organise each opportunity around the business behind it and the structure of the investment itself, giving you more to work with than a headline number.','Designed for informed participation','Clear terms, organised records and visible portfolio information help you understand what you are considering and what happens after you invest.','Research first. Allocate second.','Review the company, understand the terms, consider the duration and decide whether the opportunity belongs in your portfolio.','Build a portfolio around decisions you understand.','Create your account, explore current opportunities and invest only when the details make sense to you.'),
        ];
    }

    private function profile(string $variant,string $kicker,string $hero,string $sub,string $introTitle,string $introBody,string $whyTitle,string $whyBody,string $philosophyTitle,string $philosophyBody,string $finalTitle,string $finalBody): array
    {
        return compact('variant','kicker','hero','sub','introTitle','introBody','whyTitle','whyBody','philosophyTitle','philosophyBody','finalTitle','finalBody') + [
            'primary_cta' => 'Explore investments',
            'secondary_cta' => 'Create account',
            'trust' => ['Clear offering terms','Protected account access','Traceable transaction records','Portfolio visibility'],
            'portfolio_title' => 'Keep the full investment journey in view',
            'portfolio_body' => 'Track investment positions, transaction history, maturity information, deposits and withdrawals from one organised account.',
            'security_title' => 'Security that supports the investment experience',
            'risk_title' => 'Clarity also means being clear about risk',
            'risk_body' => 'Investing involves risk. Projected returns are illustrative terms of an offering, not guaranteed results. Review the company information, offering terms and applicable disclosures before making a decision.',
            'resources_title' => 'Build a stronger investment process',
            'featured_title' => 'Opportunities worth a closer look',
            'featured_body' => 'Review the business and the offering terms together before deciding whether an opportunity fits your objectives.',
        ];
    }

    private function securityPoints(string $variant): array
    {
        $sets = [
            'minimal' => ['Secure sign-in and session controls','Optional two-factor authentication','Protected private documents','Clear account activity records'],
            'premium' => ['Layered account access controls','Two-factor authentication support','Protected document handling','Auditable transaction records'],
            'precision' => ['Strong credential handling','Two-factor authentication support','Structured financial records','Protected private documentation'],
            'structured' => ['Secure authentication controls','Traceable account sessions','Immutable financial ledger records','Controlled private document access'],
            'vibrant' => ['Protected account access','Two-factor authentication support','Clear transaction history','Private document protection'],
            'warm' => ['Secure account access','Two-factor authentication support','Visible transaction records','Protected personal documents'],
            'modern' => ['Modern account security controls','Two-factor authentication support','Traceable transaction activity','Protected private files'],
            'editorial' => ['Secure account access','Two-factor authentication support','Clear transaction records','Protected private documentation'],
            'institutional' => ['Secure authentication controls','Two-factor authentication support','Immutable financial ledger records','Protected private documentation'],
        ];
        return $sets[$variant] ?? $sets['institutional'];
    }

    private function process(string $variant): array
    {
        return [
            ['01','Create your account','Set up secure access and complete the information required for your account.'],
            ['02','Explore opportunities','Review companies and compare the investment terms currently available to you.'],
            ['03','Review before investing','Examine price, projected outcome, duration and supporting company information before confirming.'],
            ['04','Track the position','Follow transactions, investment positions and maturity information from your account.'],
        ];
    }

    private function resources(string $variant): array
    {
        return [
            ['How to read an opportunity','Separate company facts from offering terms and understand what each tells you.'],
            ['Understanding projected returns','Treat projections as terms to evaluate, not promises of future performance.'],
            ['Think about time horizon','Consider how the investment duration fits your own liquidity needs and objectives.'],
        ];
    }

    private function faq(array $profile, array $country): array
    {
        $currency = (string)($country['currency_code'] ?? 'USD');
        return [
            ['What information can I review before investing?','Each active opportunity can include company information, investment price, projected return structure, duration, availability and supporting source information.'],
            ['Are projected returns guaranteed?','No. Projected returns describe the configured terms of an offering and are not a guarantee of investment performance.'],
            ['Which currency will I see?',"Investment amounts for your account experience are presented in {$currency} unless an individual offering states otherwise."],
            ['Can I track an investment after purchase?','Yes. Your account keeps investment positions, transactions and maturity information organised for ongoing review.'],
            ['How is my account protected?','The platform uses secure authentication controls and supports additional safeguards such as two-factor authentication.'],
        ];
    }
}
