<?php
declare(strict_types=1);namespace App\Services;use App\Support\Database;
final class KycService {
 public function __construct(private ?Database $db,private DynamicFormService $forms,private NotificationService $notifications){}
 public function configuration(array $country):?array{return $this->db?->one('SELECT * FROM kyc_configurations WHERE country_id=? AND is_active=1 ORDER BY version DESC LIMIT 1',[$country['id']]);}
 public function required(array $country):bool{return(bool)($this->configuration($country)['is_required']??false);}
 public function approved(int $userId,array $country):bool{return !$this->required($country)||(bool)$this->db?->scalar('SELECT COUNT(*) FROM kyc_submissions WHERE user_id=? AND country_id=? AND status="APPROVED" AND (expires_at IS NULL OR expires_at>NOW())',[$userId,$country['id']]);}
 public function canWithdraw(array $user,array $country):bool{return strtoupper((string)($user['account_status']??''))==='ACTIVE'&&$this->approved((int)$user['id'],$country);}
 public function current(int $userId,array $country):?array{return $this->db?->one('SELECT * FROM kyc_submissions WHERE user_id=? AND country_id=? ORDER BY created_at DESC LIMIT 1',[$userId,$country['id']]);}
 public function save(array $user,array $country,array $values,array $files,bool $submit=false):array{if(!$this->db)throw new \RuntimeException('Database unavailable.');$config=$this->configuration($country);if(!$config)throw new \RuntimeException('Identity verification is not configured for this Country Pack.');$fields=$this->forms->definition($config['form_id']?(int)$config['form_id']:null);if($submit)$this->forms->validate($fields,$values,$files);$existing=$this->current((int)$user['id'],$country);if($existing&&in_array($existing['status'],['PENDING','UNDER_REVIEW','APPROVED'],true))throw new \RuntimeException('This identity verification cannot be edited.');$result=$this->db->transaction(function(Database $db)use($user,$country,$config,$fields,$values,$submit,$existing){$id=$existing['id']??null;if(!$id){$db->execute('INSERT INTO kyc_submissions(public_id,user_id,country_id,configuration_id,configuration_version,form_snapshot_id,status) VALUES (?,?,?,?,?,?,"DRAFT")',[bin2hex(random_bytes(16)),$user['id'],$country['id'],$config['id'],$config['version'],$this->forms->snapshot($config['form_id']?(int)$config['form_id']:null,'KYC')]);$id=(int)$db->pdo()->lastInsertId();}foreach($values as$key=>$value){$field=array_values(array_filter($fields,fn($f)=>$f['field_key']===$key))[0]??null;if($field&&$field['field_type']!=='FILE')$db->execute('INSERT INTO kyc_submission_values(kyc_submission_id,field_key,field_label,value_text) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE value_text=VALUES(value_text)',[$id,$key,$field['label'],is_array($value)?implode(',',array_map('strval',$value)):(string)$value]);}$status=$submit?'PENDING':'DRAFT';$db->execute('UPDATE kyc_submissions SET status=?,submitted_at=CASE WHEN ? THEN NOW() ELSE submitted_at END,updated_at=NOW() WHERE id=?',[$status,$submit?1:0,$id]);$db->execute('INSERT INTO kyc_events(kyc_submission_id,actor_user_id,event_type) VALUES (?,?,?)',[$id,$user['id'],$submit?'SUBMITTED':'DRAFT_SAVED']);return $db->one('SELECT * FROM kyc_submissions WHERE id=?',[$id]);});if($submit)$this->notifications->transactional((int)$user['id'],'kyc_submitted','Identity verification submitted','Your identity verification is awaiting review.',['url'=>'/dashboard/kyc']);return $result;}
 public function document(int $submissionId,string $key,array $file):void{if(!$this->db)throw new \RuntimeException('Database unavailable.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name']);$size=(int)$file['size'];$name=basename((string)$file['name']);$path=app('upload')->store($file,true,false);$this->db->execute('INSERT INTO kyc_documents(kyc_submission_id,field_key,storage_path,original_filename,mime_type,file_size) VALUES (?,?,?,?,?,?)',[$submissionId,$key,$path,$name,$mime,$size]);}
 public function documents(int $submissionId):array{return $this->db?->select('SELECT * FROM kyc_documents WHERE kyc_submission_id=?',[$submissionId])??[];}
 public function review(int $id,int $adminId,string $action,string $message='',string $private=''):void{if(!$this->db)return;if(in_array($action,['REJECT','RESUBMIT'],true)&&trim($message)==='')throw new \InvalidArgumentException('A user-facing message is required.');$map=['UNDER_REVIEW'=>'UNDER_REVIEW','APPROVE'=>'APPROVED','REJECT'=>'REJECTED','RESUBMIT'=>'RESUBMISSION_REQUIRED'];$status=$map[$action]??throw new \InvalidArgumentException('Unknown KYC action.');$event=$this->db->transaction(function(Database $db)use($id,$adminId,$status,$message,$private){$submission=$db->lockForUpdate('SELECT * FROM kyc_submissions WHERE id=?',[$id]);if(!$submission)throw new \RuntimeException('KYC submission not found.');if(in_array($submission['status'],['APPROVED','REJECTED'],true))throw new \RuntimeException('This KYC submission is already closed.');$db->execute('UPDATE kyc_submissions SET status=?,reviewed_at=NOW(),reviewed_by_user_id=?,approved_at=CASE WHEN ?="APPROVED" THEN NOW() ELSE approved_at END,rejection_reason=CASE WHEN ?="REJECTED" THEN ? ELSE rejection_reason END,resubmission_message=CASE WHEN ?="RESUBMISSION_REQUIRED" THEN ? ELSE resubmission_message END,admin_notes=? WHERE id=?',[$status,$adminId,$status,$status,$message,$status,$message,$private,$id]);$db->execute('INSERT INTO kyc_events(kyc_submission_id,actor_user_id,event_type,user_message,private_note) VALUES (?,?,?,?,?)',[$id,$adminId,$status,$message,$private]);return ['user_id'=>(int)$submission['user_id'],'status'=>$status];});$titles=['UNDER_REVIEW'=>'Identity verification under review','APPROVED'=>'Identity verification approved','REJECTED'=>'Identity verification rejected','RESUBMISSION_REQUIRED'=>'Identity verification needs updates'];try{$this->notifications->transactional($event['user_id'],'kyc_'.strtolower($event['status']),$titles[$event['status']],$message,['url'=>'/dashboard/kyc']);}catch(\Throwable){/* Notification delivery must not roll back compliance decisions. */}}
}
