<?php
declare(strict_types=1);
namespace App\Services;
use App\Support\Database;
final class LicenseService {
    public function __construct(private ?Database $db) {}
    public function current(int $countryId): ?array { $row=$this->db?->one('SELECT * FROM licenses WHERE country_id=? AND is_current=1 ORDER BY created_at DESC LIMIT 1',[$countryId]);return $row?$this->withStatus($row):null; }
    public function status(?array $license,int $warningDays=30): string {if(!$license)return 'MISSING';if(($license['manual_status']??'')==='SUSPENDED')return 'SUSPENDED';if(($license['manual_status']??'')==='NOT_REQUIRED')return 'NOT_REQUIRED';if(empty($license['expiry_date']))return 'ACTIVE';$days=(int)floor((strtotime($license['expiry_date'])-strtotime('today'))/86400);return $days<0?'EXPIRED':($days<=$warningDays?'EXPIRING_SOON':'ACTIVE');}
    public function settings(int $countryId):array{return $this->db?->one('SELECT * FROM country_license_settings WHERE country_id=?',[$countryId])??['country_id'=>$countryId,'require_valid_license_for_investing'=>0,'expiry_warning_days'=>30];}
    public function canInvest(array $country):bool{$settings=$this->settings((int)$country['id']);return !(bool)$settings['require_valid_license_for_investing']||$this->status($this->current((int)$country['id']),(int)$settings['expiry_warning_days'])==='ACTIVE';}
    public function saveSettings(int $countryId,bool $required,int $days):void{$this->db?->execute('INSERT INTO country_license_settings (country_id,require_valid_license_for_investing,expiry_warning_days,updated_at) VALUES (?,?,?,NOW()) ON DUPLICATE KEY UPDATE require_valid_license_for_investing=VALUES(require_valid_license_for_investing),expiry_warning_days=VALUES(expiry_warning_days),updated_at=NOW()',[$countryId,$required?1:0,max(1,min(365,$days))]);}
    public function save(int $countryId,array $data,?array $file,int $actor):int {if(!$this->db)throw new \RuntimeException('Database unavailable.');$path=null;$mime=null;$size=null;$name=null;if($file&&($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE){$path=app('upload')->store($file,true,false);$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$size=(int)$file['size'];$name=basename((string)$file['name']);}$this->db->transaction(function()use($countryId,$data,$path,$mime,$size,$name,$actor){$this->db->execute('UPDATE licenses SET is_current=0,updated_at=NOW() WHERE country_id=? AND is_current=1',[$countryId]);$this->db->execute('INSERT INTO licenses (country_id,regulator_name,license_name,license_number,issue_date,expiry_date,manual_status,notes,document_path,original_filename,mime_type,file_size,is_current,uploaded_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,1,IF(? IS NULL,NULL,NOW()),?,NOW(),NOW())',[$countryId,$data['regulator_name']?:null,$data['license_name']?:null,$data['license_number']?:null,$data['issue_date']?:null,$data['expiry_date']?:null,$data['manual_status']?:null,$data['notes']?:null,$path,$name,$mime,$size,$path,$actor]);});return (int)$this->db->pdo()->lastInsertId();}
    private function withStatus(array $row):array{$settings=$this->settings((int)$row['country_id']);$row['calculated_status']=$this->status($row,(int)$settings['expiry_warning_days']);return $row;}
}
