<?php
declare(strict_types=1);
namespace App\Services;
use App\Repositories\UserRepository; use App\Security\Crypto; use App\Support\Database;
final class TwoFactorService {
    public function __construct(private ?Database $db,private UserRepository $users,private Crypto $crypto,private SecurityEventService $events) {}
    public function beginSetup(array $user): array { $secret=$this->base32(random_bytes(20)); $_SESSION['two_factor_setup']=['user_id'=>(int)$user['id'],'secret'=>$secret,'created_at'=>time()]; $issuer=rawurlencode((string)config('app.name')); $label=rawurlencode((string)config('app.name').':'.$user['email']); return ['secret'=>$secret,'uri'=>'otpauth://totp/'.$label.'?secret='.$secret.'&issuer='.$issuer.'&algorithm=SHA1&digits=6&period=30']; }
    public function confirmSetup(array $user,string $code): ?array { $setup=$_SESSION['two_factor_setup']??null; if(!is_array($setup)||(int)($setup['user_id']??0)!==(int)$user['id']||time()-(int)($setup['created_at']??0)>900||!$this->verify((string)$setup['secret'],$code))return null; $codes=$this->newRecoveryCodes(); $this->db?->transaction(function()use($user,$setup,$codes){$this->users->update((int)$user['id'],['two_factor_secret_encrypted'=>$this->crypto->encrypt($setup['secret']),'two_factor_enabled_at'=>date('Y-m-d H:i:s')]);$this->replaceRecoveryCodes((int)$user['id'],$codes);}); unset($_SESSION['two_factor_setup']); $this->events->record((int)$user['id'],'two_factor_enabled'); return $codes; }
    public function disable(array $user,string $code): bool { $secret=$this->secretFor($user); if(!$secret||!$this->verify($secret,$code))return false; $this->users->update((int)$user['id'],['two_factor_secret_encrypted'=>null,'two_factor_enabled_at'=>null]);$this->db?->execute('DELETE FROM two_factor_recovery_codes WHERE user_id=?',[$user['id']]);$this->events->record((int)$user['id'],'two_factor_disabled');return true; }
    public function verifyUser(array $user,string $code): bool { $secret=$this->secretFor($user); return $secret!==null && $this->verify($secret,$code); }
    public function consumeRecoveryCode(array $user,string $code): bool { if(!$this->db)return false; $hash=TokenService::hash(strtoupper(trim($code))); $changed=$this->db->execute('UPDATE two_factor_recovery_codes SET used_at=NOW() WHERE user_id=? AND code_hash=? AND used_at IS NULL',[$user['id'],$hash]); if($changed){$this->events->record((int)$user['id'],'two_factor_recovery_used');return true;} return false; }
    public function regenerate(array $user,string $code): ?array { if(!$this->verifyUser($user,$code))return null;$codes=$this->newRecoveryCodes();$this->replaceRecoveryCodes((int)$user['id'],$codes);$this->events->record((int)$user['id'],'two_factor_recovery_regenerated');return $codes; }
    public function verify(string $secret,string $code): bool { $code=preg_replace('/\s+/', '', $code)??''; if(!preg_match('/^\d{6}$/',$code))return false; $step=(int)floor(time()/30); for($i=-1;$i<=1;$i++)if(hash_equals($this->totp($secret,$step+$i),$code))return true;return false; }
    private function secretFor(array $user): ?string { $enc=(string)($user['two_factor_secret_encrypted']??''); if($enc==='')return null; try{return $this->crypto->decrypt($enc);}catch(\Throwable){return null;} }
    private function replaceRecoveryCodes(int $userId,array $codes): void { if(!$this->db)return;$this->db->execute('DELETE FROM two_factor_recovery_codes WHERE user_id=?',[$userId]);foreach($codes as $code)$this->db->execute('INSERT INTO two_factor_recovery_codes (user_id,code_hash,created_at) VALUES (?,?,NOW())',[$userId,TokenService::hash($code)]); }
    private function newRecoveryCodes(): array { $codes=[];for($i=0;$i<10;$i++)$codes[]=strtoupper(substr(TokenService::raw(8),0,4).'-'.substr(TokenService::raw(8),0,4));return $codes; }
    private function totp(string $secret,int $counter): string { $binary=$this->decode32($secret);$message=pack('N*',0,$counter);$hash=hash_hmac('sha1',$message,$binary,true);$offset=ord($hash[19])&15;$value=((ord($hash[$offset])&127)<<24)|((ord($hash[$offset+1])&255)<<16)|((ord($hash[$offset+2])&255)<<8)|(ord($hash[$offset+3])&255);return str_pad((string)($value%1000000),6,'0',STR_PAD_LEFT); }
    private function base32(string $binary): string { $alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$bits='';foreach(str_split($binary)as$c)$bits.=str_pad(decbin(ord($c)),8,'0',STR_PAD_LEFT);$out='';foreach(str_split($bits,5)as$chunk){if(strlen($chunk)<5)$chunk=str_pad($chunk,5,'0');$out.=$alphabet[bindec($chunk)];}return $out; }
    private function decode32(string $value): string { $alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';$value=strtoupper(preg_replace('/[^A-Z2-7]/','',$value)??'');$bits='';foreach(str_split($value)as$c){$p=strpos($alphabet,$c);if($p===false)throw new \InvalidArgumentException('Invalid TOTP secret.');$bits.=str_pad(decbin($p),5,'0',STR_PAD_LEFT);}$out='';foreach(str_split($bits,8)as$chunk){if(strlen($chunk)===8)$out.=chr(bindec($chunk));}return $out; }
}
