<?php
declare(strict_types=1);
namespace App\Services;
use App\Support\Database;

/** The only service permitted to mutate materialized wallet balances. */
final class WalletService {
 public function __construct(private ?Database $db){}
 public function walletFor(array $user,array $country):?array{if(!$this->db)return null;$wallet=$this->db->one('SELECT * FROM wallets WHERE user_id=?',[(int)$user['id']]);if($wallet)return $wallet;$this->db->execute('INSERT INTO wallets(user_id,country_id,currency_code) VALUES (?,?,?)',[(int)$user['id'],(int)$country['id'],(string)$country['currency_code']]);return $this->db->one('SELECT * FROM wallets WHERE id=?',[(int)$this->db->pdo()->lastInsertId()]);}
 public function balance(int $userId):array{return $this->db?->one('SELECT * FROM wallets WHERE user_id=?',[$userId])??['available_balance_minor'=>0,'reserved_balance_minor'=>0,'currency_code'=>'USD'];}
 public function history(int $userId,array $filters=[],int $page=1,int $perPage=20):array{if(!$this->db)return ['items'=>[],'total'=>0];$where=['user_id=?'];$params=[$userId];foreach(['transaction_type'=>'type','status'=>'status'] as $column=>$key)if(($filters[$key]??'')!==''){$where[]=$column.'=?';$params[]=$filters[$key];}if(($filters['q']??'')!==''){$where[]='(reference LIKE ? OR description LIKE ?)';$params[]='%'.$filters['q'].'%';$params[]='%'.$filters['q'].'%';}$sql=implode(' AND ',$where);$total=(int)$this->db->scalar('SELECT COUNT(*) FROM ledger_transactions WHERE '.$sql,$params);$params[]=max(0,($page-1)*$perPage);$params[]=$perPage;return ['items'=>$this->db->select('SELECT * FROM ledger_transactions WHERE '.$sql.' ORDER BY created_at DESC LIMIT ?,?',$params),'total'=>$total];}
 public function move(int $walletId,string $type,string $direction,int $amount,string $description,string $relatedType,?string $relatedId,?int $actor=null,?string $reason=null):array{if(!$this->db)throw new \RuntimeException('Database unavailable.');if($amount<=0||!in_array($direction,['CREDIT','DEBIT'],true))throw new \InvalidArgumentException('Invalid financial movement.');return $this->db->transaction(function(Database $db)use($walletId,$type,$direction,$amount,$description,$relatedType,$relatedId,$actor,$reason){$wallet=$db->lockForUpdate('SELECT * FROM wallets WHERE id=?',[$walletId]);if(!$wallet||$wallet['status']!=='ACTIVE')throw new \RuntimeException('Wallet is unavailable.');if($relatedType!==''&&$relatedId!==null){$old=$db->one('SELECT * FROM ledger_transactions WHERE related_entity_type=? AND related_entity_id=? AND transaction_type=?',[$relatedType,$relatedId,$type]);if($old)return ['id'=>(int)$old['id'],'reference'=>$old['reference'],'before'=>(int)$old['balance_before_minor'],'after'=>(int)$old['balance_after_minor'],'idempotent'=>true];}$before=(int)$wallet['available_balance_minor'];$after=$direction==='CREDIT'?$before+$amount:$before-$amount;if($after<0)throw new \RuntimeException('Insufficient available balance.');$ref=$this->reference($this->prefix($type));$db->execute('INSERT INTO ledger_transactions(public_id,reference,user_id,wallet_id,country_id,currency_code,transaction_type,direction,amount_minor,balance_before_minor,balance_after_minor,related_entity_type,related_entity_id,description,metadata,created_by_type,created_by_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$this->uuid(),$ref,$wallet['user_id'],$walletId,$wallet['country_id'],$wallet['currency_code'],$type,$direction,$amount,$before,$after,$relatedType?:null,$relatedId,$description,json_encode(['reason'=>$reason]),$actor?'ADMIN':'SYSTEM',$actor]);$id=(int)$db->pdo()->lastInsertId();$db->execute('UPDATE wallets SET available_balance_minor=?,updated_at=NOW() WHERE id=?',[$after,$walletId]);return ['id'=>$id,'reference'=>$ref,'before'=>$before,'after'=>$after,'idempotent'=>false];});}
 public function reserve(int $walletId,int $amount,string $purpose,string $relatedType='',?string $relatedId=null):array{if(!$this->db||$amount<=0)throw new \InvalidArgumentException('A positive reservation amount is required.');return $this->db->transaction(function(Database $db)use($walletId,$amount,$purpose,$relatedType,$relatedId){if($relatedType!==''&&$relatedId!==null){$old=$db->one('SELECT * FROM wallet_reservations WHERE related_entity_type=? AND related_entity_id=? AND status="ACTIVE"',[$relatedType,$relatedId]);if($old)return ['id'=>(int)$old['id'],'reference'=>$old['public_id'],'idempotent'=>true];}$wallet=$db->lockForUpdate('SELECT * FROM wallets WHERE id=?',[$walletId]);if(!$wallet||$wallet['status']!=='ACTIVE'||(int)$wallet['available_balance_minor']<$amount)throw new \RuntimeException('Insufficient available balance.');$ref=$this->uuid();$db->execute('UPDATE wallets SET available_balance_minor=available_balance_minor-?,reserved_balance_minor=reserved_balance_minor+?,updated_at=NOW() WHERE id=?',[$amount,$amount,$walletId]);$db->execute('INSERT INTO wallet_reservations(public_id,wallet_id,user_id,amount_minor,purpose,related_entity_type,related_entity_id) VALUES (?,?,?,?,?,?,?)',[$ref,$walletId,$wallet['user_id'],$amount,$purpose,$relatedType?:null,$relatedId]);return ['id'=>(int)$db->pdo()->lastInsertId(),'reference'=>$ref,'idempotent'=>false];});}
 public function release(int $reservationId):void{if(!$this->db)return;$this->db->transaction(function(Database $db)use($reservationId){$r=$db->lockForUpdate('SELECT * FROM wallet_reservations WHERE id=?',[$reservationId]);if(!$r||$r['status']!=='ACTIVE')throw new \RuntimeException('Reservation is not active.');$db->lockForUpdate('SELECT * FROM wallets WHERE id=?',[(int)$r['wallet_id']]);$db->execute('UPDATE wallets SET available_balance_minor=available_balance_minor+?,reserved_balance_minor=reserved_balance_minor-?,updated_at=NOW() WHERE id=?',[$r['amount_minor'],$r['amount_minor'],$r['wallet_id']]);$db->execute('UPDATE wallet_reservations SET status="RELEASED",released_at=NOW() WHERE id=?',[$reservationId]);});}
 /** Convert a reservation into one debit without deducting available balance again. */
 public function consume(int $reservationId,string $type,string $description,string $relatedType,string $relatedId,?int $actor=null):array{if(!$this->db)throw new \RuntimeException('Database unavailable.');return $this->db->transaction(function(Database $db)use($reservationId,$type,$description,$relatedType,$relatedId,$actor){$r=$db->lockForUpdate('SELECT * FROM wallet_reservations WHERE id=?',[$reservationId]);if(!$r)throw new \RuntimeException('Reservation not found.');$wallet=$db->lockForUpdate('SELECT * FROM wallets WHERE id=?',[(int)$r['wallet_id']]);if($r['status']==='CONSUMED'){$old=$db->one('SELECT * FROM ledger_transactions WHERE related_entity_type=? AND related_entity_id=? AND transaction_type=?',[$relatedType,$relatedId,$type]);if($old)return ['id'=>(int)$old['id'],'reference'=>$old['reference'],'idempotent'=>true];}if($r['status']!=='ACTIVE'||!$wallet)throw new \RuntimeException('Reservation is unavailable.');$before=(int)$wallet['available_balance_minor'];$ref=$this->reference($this->prefix($type));$db->execute('INSERT INTO ledger_transactions(public_id,reference,user_id,wallet_id,country_id,currency_code,transaction_type,direction,amount_minor,balance_before_minor,balance_after_minor,related_entity_type,related_entity_id,description,metadata,created_by_type,created_by_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$this->uuid(),$ref,$wallet['user_id'],$wallet['id'],$wallet['country_id'],$wallet['currency_code'],$type,'DEBIT',$r['amount_minor'],$before,$before,$relatedType,$relatedId,$description,'{}',$actor?'ADMIN':'SYSTEM',$actor]);$id=(int)$db->pdo()->lastInsertId();$db->execute('UPDATE wallets SET reserved_balance_minor=reserved_balance_minor-?,updated_at=NOW() WHERE id=?',[$r['amount_minor'],$wallet['id']]);$db->execute('UPDATE wallet_reservations SET status="CONSUMED",released_at=NOW() WHERE id=?',[$reservationId]);return ['id'=>$id,'reference'=>$ref,'idempotent'=>false];});}
 public function exposure(int $userId):bool{if(!$this->db)return false;return(bool)$this->db->scalar('SELECT COUNT(*) FROM ledger_transactions WHERE user_id=?',[$userId])||(bool)$this->db->scalar('SELECT COUNT(*) FROM wallet_reservations WHERE user_id=? AND status="ACTIVE"',[$userId]);}
 private function prefix(string $type):string{return match($type){'DEPOSIT'=>'DEP','WITHDRAWAL'=>'WDR','INVESTMENT_PURCHASE'=>'INV','SHARE_SALE'=>'SAL','ADMIN_CREDIT','ADMIN_DEBIT','ADJUSTMENT','REVERSAL'=>'ADM',default=>'TXN'};}private function reference(string $prefix):string{return $prefix.'-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(6)));}private function uuid():string{return bin2hex(random_bytes(16));}
}
