<?php
declare(strict_types=1);
namespace Database\Seeds;
use App\Support\Database;

/**
 * Curated factual seed set. Records are idempotent by seed_key and deliberately
 * do not overwrite administrator-edited listings on a repeat production run.
 */
final class CompanySeeder {
    public function run(Database $db): void { foreach($this->records() as $record){$country=$db->one('SELECT id,currency_code FROM countries WHERE slug=? AND is_enabled=1',[$record['country']]);if(!$country)continue;$exists=$db->one('SELECT id FROM companies WHERE seed_key=?',[$record['key']]);if($exists)continue;$db->transaction(function(Database $db)use($record,$country):void{$db->execute('INSERT INTO companies(public_id,seed_key,legal_name,display_name,slug,ticker,stock_exchange,exchange_mic,listing_country_code,headquarters_country_code,headquarters_city,sector,industry,website_url,investor_relations_url,short_description,status,last_verified_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"ACTIVE",CURDATE(),NOW(),NOW())',[$this->uuid(),$record['key'],$record['legal'],$record['name'],$record['slug'],$record['ticker'],$record['exchange'],$record['mic'],$record['listing_country'],$record['hq_country'],$record['city'],$record['sector'],$record['industry'],$record['website'],$record['ir'],$record['description']]);$id=(int)$db->pdo()->lastInsertId();$db->execute('INSERT INTO company_country_assignments(company_id,country_id) VALUES (?,?)',[$id,$country['id']]);$db->execute('INSERT INTO investment_offerings(public_id,company_id,country_id,currency_code,share_price_minor,minimum_purchase_quantity,fractional_shares_allowed,quantity_decimal_places,profit_type,projected_profit_value,duration_value,duration_unit,selling_enabled,is_active,is_featured,created_at,updated_at) VALUES (?,?,?,?,?,1,0,0,"PERCENTAGE",12.50,180,"DAYS",0,1,1,NOW(),NOW())',[$this->uuid(),$id,$country['id'],$country['currency_code'],$record['offering_price_minor']]);foreach($record['sources'] as $source)$db->execute('INSERT INTO company_sources(company_id,source_type,title,source_url,publisher,verified_at) VALUES (?,?,?,?,?,CURDATE())',[$id,$source[0],$source[1],$source[2],$source[3]]);});}}
    private function records():array{return [
        ['key'=>'sg-aem-awx','country'=>'singapore','legal'=>'AEM Holdings Ltd.','name'=>'AEM Holdings','slug'=>'aem-holdings','ticker'=>'AWX','exchange'=>'Singapore Exchange Mainboard','mic'=>'XSES','listing_country'=>'SG','hq_country'=>'SG','city'=>'Singapore','sector'=>'Technology','industry'=>'Semiconductor test solutions','website'=>'https://www.aem.com.sg/','ir'=>'https://investors.aem.com.sg/','description'=>'Semiconductor and electronics test solutions provider.','offering_price_minor'=>1250,'sources'=>[['STOCK_EXCHANGE','SGX corporate information: AEM Holdings Ltd.','https://links.sgx.com/1.0.0/corporate-information/2648','Singapore Exchange'],['OFFICIAL_COMPANY','AEM investor relations','https://investors.aem.com.sg/','AEM Holdings']]],
        ['key'=>'ph-dnl','country'=>'philippines','legal'=>'D&L Industries, Inc.','name'=>'D&L Industries','slug'=>'dl-industries','ticker'=>'DNL','exchange'=>'Philippine Stock Exchange','mic'=>'XPHS','listing_country'=>'PH','hq_country'=>'PH','city'=>'Quezon City','sector'=>'Materials','industry'=>'Specialty chemicals','website'=>'https://www.dnl.com.ph/','ir'=>'https://www.dnl.com.ph/investor-relations/','description'=>'Philippine manufacturer of specialty products and chemicals.','offering_price_minor'=>700,'sources'=>[['STOCK_EXCHANGE','PSE disclosure: D&L Industries, Inc.','https://edge.pse.com.ph/downloadHtml.do?file_id=1926254','Philippine Stock Exchange'],['OFFICIAL_COMPANY','D&L Industries investor relations','https://www.dnl.com.ph/investor-relations/','D&L Industries']]],
        ['key'=>'tt-ghl','country'=>'trinidad-and-tobago','legal'=>'Guardian Holdings Limited','name'=>'Guardian Holdings','slug'=>'guardian-holdings','ticker'=>'GHL','exchange'=>'Trinidad and Tobago Stock Exchange','mic'=>'XTRN','listing_country'=>'TT','hq_country'=>'TT','city'=>'Port of Spain','sector'=>'Financials','industry'=>'Insurance','website'=>'https://www.myguardiangroup.com/','ir'=>'https://www.myguardiangroup.com/','description'=>'Caribbean insurance and financial-services group.','offering_price_minor'=>2500,'sources'=>[['REGULATORY','TTSEC matter referencing Guardian Holdings Limited (GHL)','https://www.ttsec.org.tt/settlement-agreement-ttsec-ncbjghl-21-09-2018/','Trinidad and Tobago Securities and Exchange Commission'],['OFFICIAL_COMPANY','Guardian Group','https://www.myguardiangroup.com/','Guardian Holdings']]],
        ['key'=>'global-aem-awx','country'=>'global','legal'=>'AEM Holdings Ltd.','name'=>'AEM Holdings International','slug'=>'aem-holdings-international','ticker'=>'AWX','exchange'=>'Singapore Exchange Mainboard','mic'=>'XSES','listing_country'=>'SG','hq_country'=>'SG','city'=>'Singapore','sector'=>'Technology','industry'=>'Semiconductor test solutions','website'=>'https://www.aem.com.sg/','ir'=>'https://investors.aem.com.sg/','description'=>'International semiconductor test-solutions company selected for the distinct Global catalogue.','offering_price_minor'=>1200,'sources'=>[['STOCK_EXCHANGE','SGX corporate information: AEM Holdings Ltd.','https://links.sgx.com/1.0.0/corporate-information/2648','Singapore Exchange'],['OFFICIAL_COMPANY','AEM investor relations','https://investors.aem.com.sg/','AEM Holdings']]],
    ];}
    private function uuid():string{return sprintf('%08x-%04x-%04x-%04x-%012x',random_int(0,0xffffffff),random_int(0,0xffff),random_int(0,0xffff),random_int(0,0xffff),random_int(0,0xfffffff));}
}
