<?php
declare(strict_types=1);

namespace Database\Seeds;

use App\Support\Database;

final class DepositMethodSeeder
{
    public function run(Database $db): void
    {
        $methods=[
            [
                'name'=>'Bank Transfer',
                'slug'=>'bank-transfer',
                'type'=>'BANK',
                'description'=>'International bank transfer using SWIFT/BIC beneficiary details configured by ApexTrades.',
                'instructions'=>'Send the exact transfer amount using the beneficiary details shown on the deposit page. Use your ApexTrades account name or transfer reference where your bank allows it. International, correspondent and intermediary bank charges are normally paid by the sender. Upload your transfer confirmation after payment.',
                'processing'=>'1–3 business days',
                'details'=>[
                    'beneficiary_name'=>'',
                    'bank_name'=>'',
                    'account_iban'=>'',
                    'swift_bic'=>'',
                    'routing_aba'=>'',
                    'bank_address'=>'',
                    'beneficiary_address'=>'',
                ],
                'fields'=>[
                    ['sender_name','TEXT','Sender / account holder name','Name on the sending bank account','Enter the name used for the transfer.',1],
                    ['sending_bank','TEXT','Sending bank','Bank or financial institution used','',1],
                    ['transfer_reference','TEXT','Transfer reference','Bank transfer reference / confirmation number','Enter the reference supplied by your bank.',1],
                    ['proof_of_payment','FILE','Transfer receipt','Upload transfer receipt','Upload the bank transfer confirmation or receipt.',1],
                ],
            ],
            [
                'name'=>'Bitcoin Deposit',
                'slug'=>'bitcoin-deposit',
                'type'=>'CRYPTO',
                'description'=>'Deposit Bitcoin to the configured ApexTrades Bitcoin wallet.',
                'instructions'=>'Send BTC only through the Bitcoin network to the wallet address shown below. Sending another asset or using an incompatible network may result in permanent loss. After sending, enter the transaction hash so the deposit can be reviewed.',
                'processing'=>'After required network confirmations',
                'details'=>[
                    'asset'=>'BTC',
                    'network'=>'Bitcoin Mainnet',
                    'wallet_address'=>'',
                ],
                'fields'=>[
                    ['sender_wallet','TEXT','Sending wallet address','Optional sending wallet address','Enter the wallet address you sent from when available.',0],
                    ['transaction_hash','TEXT','Transaction hash / TXID','Bitcoin transaction ID','Enter the transaction hash generated by your wallet.',1],
                    ['payment_proof','FILE','Payment screenshot','Optional screenshot','You may upload a wallet or explorer screenshot.',0],
                ],
            ],
            [
                'name'=>'USDT Deposit',
                'slug'=>'usdt-deposit',
                'type'=>'CRYPTO',
                'description'=>'Deposit USDT to the configured ApexTrades wallet on the selected network.',
                'instructions'=>'Send USDT only on the network displayed with the wallet address. The token and network must both match. Sending USDT through another network or sending another asset may result in permanent loss. Enter the transaction hash after sending.',
                'processing'=>'After required network confirmations',
                'details'=>[
                    'asset'=>'USDT',
                    'network'=>'TRC20 (Tron)',
                    'wallet_address'=>'',
                ],
                'fields'=>[
                    ['sender_wallet','TEXT','Sending wallet address','Optional sending wallet address','Enter the wallet address you sent from when available.',0],
                    ['transaction_hash','TEXT','Transaction hash / TXID','USDT transaction ID','Enter the transaction hash generated by your wallet.',1],
                    ['payment_proof','FILE','Payment screenshot','Optional screenshot','You may upload a wallet or explorer screenshot.',0],
                ],
            ],
        ];

        foreach($methods as $definition){
            $formKey='deposit_'.$definition['slug'];
            $db->execute(
                'INSERT INTO dynamic_forms(name,form_key,purpose,active,created_at,updated_at) VALUES (?,?,\'DEPOSIT\',1,NOW(),NOW()) ON DUPLICATE KEY UPDATE active=1,updated_at=NOW()',
                [$definition['name'].' Details',$formKey]
            );
            $formId=(int)$db->scalar('SELECT id FROM dynamic_forms WHERE form_key=? LIMIT 1',[$formKey]);

            $method=$db->one('SELECT * FROM deposit_methods WHERE slug=? LIMIT 1',[$definition['slug']]);
            if(!$method){
                $db->execute(
                    'INSERT INTO deposit_methods(public_id,name,slug,method_type,description,instructions,payment_details,enabled,minimum_amount_minor,maximum_amount_minor,fee_type,fee_value,fee_behavior,estimated_processing_time,form_id,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,0,0,NULL,\'NONE\',0,\'DEDUCT_FROM_CREDIT\',?,?,0,NOW(),NOW())',
                    [$this->uuid(),$definition['name'],$definition['slug'],$definition['type'],$definition['description'],$definition['instructions'],json_encode($definition['details'],JSON_THROW_ON_ERROR),$definition['processing'],$formId]
                );
                $methodId=(int)$db->pdo()->lastInsertId();
            }else{
                $methodId=(int)$method['id'];
                if(empty($method['form_id'])){
                    $db->execute('UPDATE deposit_methods SET form_id=?,updated_at=NOW() WHERE id=?',[$formId,$methodId]);
                }
            }

            foreach($definition['fields'] as $index=>$field){
                [$key,$type,$label,$placeholder,$help,$required]=$field;
                $db->execute(
                    'INSERT INTO dynamic_form_fields(form_id,field_key,field_type,label,placeholder,help_text,is_required,is_user_editable,is_visible,sort_order,max_file_size,created_at,updated_at) VALUES (?,?,?,?,?,?,?,1,1,?,CASE WHEN ?=\'FILE\' THEN 20971520 ELSE NULL END,NOW(),NOW()) ON DUPLICATE KEY UPDATE updated_at=NOW()',
                    [$formId,$key,$type,$label,$placeholder?:null,$help?:null,$required,($index+1)*10,$type]
                );
            }

            foreach($db->select('SELECT id FROM countries WHERE is_global=1 OR (is_active=1 AND is_enabled=1)') as $country){
                $db->execute(
                    'INSERT IGNORE INTO deposit_method_countries(deposit_method_id,country_id) VALUES (?,?)',
                    [$methodId,(int)$country['id']]
                );
            }
        }
    }

    private function uuid(): string
    {
        $b=random_bytes(16);
        $b[6]=chr((ord($b[6])&0x0f)|0x40);
        $b[8]=chr((ord($b[8])&0x3f)|0x80);
        $h=bin2hex($b);
        return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20,12);
    }
}
