<?php
declare(strict_types=1);
namespace App\Validation;
final class Validator {
    private array $errors = [], $validated = [];
    public function __construct(private readonly array $data, private readonly array $files = []) {}
    public function validate(array $rules): array { foreach ($rules as $field => $list) { $ruleset = is_string($list) ? explode('|', $list) : $list; $value = $this->data[$field] ?? null; $empty = $value === null || $value === ''; foreach ($ruleset as $rule) { [$name, $arg] = array_pad(explode(':', $rule, 2), 2, null); if ($name === 'optional' && $empty) break; if ($name === 'required' && $empty) $this->fail($field, 'is required'); elseif (!$empty && !$this->passes($name, $value, $arg, $field)) $this->fail($field, 'is invalid'); } if (!isset($this->errors[$field]) && !$empty) $this->validated[$field] = $value; } return $this->validated; }
    public function fails(): bool { return $this->errors !== []; } public function errors(): array { return $this->errors; }
    private function passes(string $rule, mixed $value, ?string $arg, string $field): bool { return match($rule) { 'required','optional' => true, 'email' => filter_var($value, FILTER_VALIDATE_EMAIL) !== false, 'min' => mb_strlen((string)$value) >= (int)$arg, 'max' => mb_strlen((string)$value) <= (int)$arg, 'numeric' => is_numeric($value), 'integer' => filter_var($value, FILTER_VALIDATE_INT) !== false, 'decimal' => preg_match('/^-?\d+(\.\d+)?$/', (string)$value) === 1, 'date' => strtotime((string)$value) !== false, 'url' => filter_var($value, FILTER_VALIDATE_URL) !== false, 'in' => in_array((string)$value, explode(',', (string)$arg), true), 'confirmed' => hash_equals((string)$value, (string)($this->data[$field . '_confirmation'] ?? '')), 'accepted' => in_array(strtolower((string)$value), ['1','true','on','yes'], true), 'strong_password' => strlen((string)$value) >= 12 && preg_match('/[a-z]/',(string)$value) && preg_match('/[A-Z]/',(string)$value) && preg_match('/\d/',(string)$value), 'file' => isset($this->files[$field]) && ($this->files[$field]['error'] ?? UPLOAD_ERR_NO_FILE) === UPLOAD_ERR_OK, 'file_size' => isset($this->files[$field]) && (int)$this->files[$field]['size'] <= (int)$arg, 'mimes' => isset($this->files[$field]) && in_array((new \finfo(FILEINFO_MIME_TYPE))->file($this->files[$field]['tmp_name']), explode(',', (string)$arg), true), default => throw new \InvalidArgumentException("Unknown validation rule [$rule].") }; }
    private function fail(string $field, string $message): void { $this->errors[$field][] = ucfirst(str_replace('_', ' ', $field)) . ' ' . $message . '.'; }
}
