<?php
declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
use App\Data\CountryContext; use App\Data\GeoLocation; use App\Repositories\ArrayCountryRepository; use App\Security\{Crypto,Csrf,PasswordHasher}; use App\Services\{AccountAccessService,CountryAccessService,CountryResolver,CountryService,GeoLocationService,LanguageService,LegalService,LicenseService,ThemeService,TokenService,Translator,TwoFactorService}; use App\Support\{Logger,Money,Request,Response,Router}; use App\Validation\Validator;
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
test('money uses exact integer minor units', function (): void { $a = Money::parse('10.25'); expect($a->minor === 1025); expect($a->percentage(1250)->minor === 128); expect($a->add(Money::parse('1.75'))->minor === 1200); });
test('validation reports malformed emails', function (): void { $v = new Validator(['email' => 'not-an-email']); $v->validate(['email' => 'required|email']); expect($v->fails()); });
test('registration validation requires confirmation, acceptance and a strong password', function (): void { $v=new Validator(['password'=>'Weakpass1','password_confirmation'=>'Weakpass2','terms'=>'0','privacy'=>'on']); $v->validate(['password'=>'required|strong_password|confirmed','terms'=>'required|accepted','privacy'=>'required|accepted']); expect($v->fails()); });
test('password hashes verify safely and incorrect passwords fail', function (): void { $hash=PasswordHasher::hash('VeryStrongPass123'); expect(PasswordHasher::verify('VeryStrongPass123',$hash)); expect(!PasswordHasher::verify('WrongPass123',$hash)); });
test('encrypted two-factor material round-trips without exposing plaintext', function (): void { $crypto=new Crypto('base64:'.base64_encode(random_bytes(32)));$encrypted=$crypto->encrypt('JBSWY3DPEHPK3PXP');expect($encrypted!=='JBSWY3DPEHPK3PXP');expect($crypto->decrypt($encrypted)==='JBSWY3DPEHPK3PXP'); });
test('TOTP accepts a current valid code and rejects an invalid code', function (): void { $service=new TwoFactorService(null,new \App\Repositories\UserRepository(null),new Crypto('base64:'.base64_encode(random_bytes(32))),new \App\Services\SecurityEventService(null,new Logger(sys_get_temp_dir().'/upgradedbroker-test-logs')));$method=(new ReflectionClass($service))->getMethod('totp');$code=$method->invoke($service,'JBSWY3DPEHPK3PXP',(int)floor(time()/30));expect($service->verify('JBSWY3DPEHPK3PXP',$code));expect(!$service->verify('JBSWY3DPEHPK3PXP','000000')); });
test('random security tokens hash without retaining their plaintext', function (): void { $token=TokenService::raw();expect(strlen($token)>20 && TokenService::hash($token)!==$token); });
test('suspended and restricted accounts cannot perform financial actions', function (): void { $access=new AccountAccessService();expect(!$access->mayPerformFinancialAction(['account_status'=>'suspended']));expect(!$access->mayPerformFinancialAction(['account_status'=>'restricted']));expect($access->mayPerformFinancialAction(['account_status'=>'active'])); });
test('csrf token verifies with timing-safe implementation', function (): void { $csrf = new Csrf(); expect($csrf->verify($csrf->token())); });
test('router resolves parameterized named routes', function (): void { $router = new Router(); app()->set('router', $router); app()->set('config', ['app' => ['url' => 'http://example.test']]); $router->get('/companies/{symbol}', fn() => new Response('ok'), 'company.show'); expect(route('company.show', ['symbol' => 'ACME']) === 'http://example.test/companies/ACME'); });

$countries = [
    ['id'=>1,'code'=>'GB','slug'=>'uk','name'=>'United Kingdom','currency_code'=>'GBP','currency_symbol'=>'£','currency_symbol_position'=>'before','locale'=>'en','timezone'=>'Europe/London','is_global'=>0,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
    ['id'=>2,'code'=>'DE','slug'=>'germany','name'=>'Germany','currency_code'=>'EUR','currency_symbol'=>'€','currency_symbol_position'=>'before','locale'=>'de-DE','timezone'=>'Europe/Berlin','is_global'=>0,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
    ['id'=>3,'code'=>'SG','slug'=>'singapore','name'=>'Singapore','currency_code'=>'SGD','currency_symbol'=>'S$','currency_symbol_position'=>'before','locale'=>'en','timezone'=>'Asia/Singapore','is_global'=>0,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
    ['id'=>4,'code'=>'PH','slug'=>'philippines','name'=>'Philippines','currency_code'=>'PHP','currency_symbol'=>'₱','currency_symbol_position'=>'before','locale'=>'en','timezone'=>'Asia/Manila','is_global'=>0,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
    ['id'=>5,'code'=>'TT','slug'=>'trinidad-and-tobago','name'=>'Trinidad and Tobago','currency_code'=>'TTD','currency_symbol'=>'TT$','currency_symbol_position'=>'before','locale'=>'en','timezone'=>'America/Port_of_Spain','is_global'=>0,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
    ['id'=>99,'code'=>null,'slug'=>'global','name'=>'Global','currency_code'=>'USD','currency_symbol'=>'$','currency_symbol_position'=>'before','locale'=>'en','timezone'=>'UTC','is_global'=>1,'is_active'=>1,'is_enabled'=>1,'theme'=>[]],
];
$languages = [2=>[['code'=>'de','locale'=>'de-DE','name'=>'German','native_name'=>'Deutsch','is_default'=>true],['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>false]],1=>[['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>true]],3=>[['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>true]],4=>[['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>true],['code'=>'fil','locale'=>'fil-PH','name'=>'Filipino','native_name'=>'Filipino','is_default'=>false]],5=>[['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>true]],99=>[['code'=>'en','locale'=>'en','name'=>'English','native_name'=>'English','is_default'=>true]]];
$repository = new ArrayCountryRepository($countries, $languages); $service = new CountryService($repository); $geo = new GeoLocationService(['driver'=>'cloudflare','trust_cloudflare_country_header'=>true,'trusted_proxies'=>['203.0.113.9']]); $resolver = new CountryResolver($service,$geo,true); $languageService = new LanguageService($service);
$requestFor = static function (string $code): Request { return new Request('GET','/',[],[],[],['REMOTE_ADDR'=>'203.0.113.9','HTTP_CF_IPCOUNTRY'=>$code]); };
test('supported GeoIP resolves Germany', function () use ($resolver,$requestFor): void { expect($resolver->resolve($requestFor('DE'))->name() === 'Germany'); });
test('unsigned guest browser follows current IP instead of stale session country', function () use ($resolver,$requestFor): void { $_SESSION['country_id']=1; $first=$resolver->resolve($requestFor('DE')); $second=$resolver->resolve($requestFor('SG')); unset($_SESSION['country_id']); expect($first->name()==='Germany' && $second->name()==='Singapore'); });
test('server-signed browser market lock overrides later guest IP changes', function () use ($resolver,$requestFor): void { $locked=$resolver->resolve($requestFor('SG'),null,2); expect($locked->name()==='Germany' && $locked->resolutionSource==='browser_account_lock'); });
test('supported GeoIP resolves Singapore', function () use ($resolver,$requestFor): void { expect($resolver->resolve($requestFor('SG'))->name() === 'Singapore'); });
test('supported GeoIP resolves Philippines', function () use ($resolver,$requestFor): void { expect($resolver->resolve($requestFor('PH'))->name() === 'Philippines'); });
test('supported GeoIP resolves Trinidad and Tobago', function () use ($resolver,$requestFor): void { expect($resolver->resolve($requestFor('TT'))->name() === 'Trinidad and Tobago'); });
test('Nigeria, Kenya, Ghana and Argentina resolve to Global', function () use ($resolver,$requestFor): void { foreach (['NG','KE','GH','AR'] as $code) expect($resolver->resolve($requestFor($code))->isGlobal(), "$code must receive Global"); });
test('unknown and failed GeoIP resolve to Global', function () use ($resolver,$requestFor,$service): void { expect($resolver->resolve($requestFor('ZZ'))->isGlobal()); $failed = new CountryResolver($service, new GeoLocationService(['driver'=>'maxmind']), false); expect($failed->resolve(new Request('GET','/',[],[],[],['REMOTE_ADDR'=>'127.0.0.1']))->isGlobal()); });
test('disabled Country Pack falls back to Global', function () use ($repository,$resolver,$requestFor): void { $repository->setEnabled('DE', false); expect($resolver->resolve($requestFor('DE'))->isGlobal()); $repository->setEnabled('DE', true); });
test('authenticated assignment overrides physical GeoIP', function () use ($resolver,$requestFor): void { $context=$resolver->resolve($requestFor('DE'),['id'=>7,'assigned_country_id'=>1,'country_id'=>2]); expect($context->name()==='United Kingdom'); });
test('language selection does not alter Country Pack or currency', function () use ($resolver,$requestFor,$languageService): void { $context=$resolver->resolve($requestFor('DE'),['id'=>7,'country_id'=>2,'preferred_language_code'=>'en']); $localized=$languageService->resolve($context,$requestFor('DE'),['preferred_language_code'=>'en']); expect($localized->name()==='Germany' && $localized->currencyCode()==='EUR' && $localized->languageCode==='en'); });
test('cross-country access is rejected server-side', function () use ($resolver,$requestFor): void { $context=$resolver->resolve($requestFor('DE')); $denied=false; try { (new CountryAccessService())->assertAccess($context,1); } catch (\App\Exceptions\HttpException $e) { $denied=$e->status===404; } expect($denied); });
test('Global-assigned user remains Global regardless of GeoIP', function () use ($resolver,$requestFor): void { expect($resolver->resolve($requestFor('DE'),['id'=>7,'assigned_country_id'=>99])->isGlobal()); });
test('untrusted Cloudflare header cannot choose a country', function () use ($service): void { $resolver=new CountryResolver($service,new GeoLocationService(['driver'=>'cloudflare','trust_cloudflare_country_header'=>false,'trusted_proxies'=>[]])); expect($resolver->resolve(new Request('GET','/',[],[],[],['REMOTE_ADDR'=>'198.51.100.10','HTTP_CF_IPCOUNTRY'=>'DE']))->isGlobal()); });
test('translator falls back from missing country language strings to English', function (): void { $t = new Translator(BASE_PATH . '/resources/lang',['en','de']); expect($t->get('dashboard.balance','de','de') === 'Available balance'); });
test('theme sanitizer rejects CSS injection attempts', function (): void { $theme=(new ThemeService())->sanitize(['primary'=>'red;body{display:none}','radius'=>'99px']); expect($theme['primary']==='#1258D5' && $theme['radius']==='18px'); });
test('legal sanitizer keeps safe formatting and removes scripts and handlers', function (): void { $safe=(new LegalService(null))->sanitize('<h2 onclick="bad()">Heading</h2><script>alert(1)</script><p><strong>Safe</strong> <a href="javascript:bad()">link</a></p>');expect(!str_contains($safe,'script')&&!str_contains($safe,'onclick')&&str_contains($safe,'<strong>Safe</strong>')); });
test('license status and eligibility rules are deterministic', function (): void { $service=new LicenseService(null);expect($service->status(null)==='MISSING');expect($service->status(['manual_status'=>null,'expiry_date'=>date('Y-m-d',strtotime('-1 day'))])==='EXPIRED');expect($service->status(['manual_status'=>null,'expiry_date'=>date('Y-m-d',strtotime('+5 days'))],30)==='EXPIRING_SOON');expect($service->status(['manual_status'=>null,'expiry_date'=>date('Y-m-d',strtotime('+90 days'))],30)==='ACTIVE');expect($service->status(['manual_status'=>'SUSPENDED','expiry_date'=>null])==='SUSPENDED'); });
test('offering validation rejects invalid price, duration and contradictory quantity settings',function():void{$v=new \App\Services\OfferingValidator();$errors=$v->validate(['share_price'=>'0','minimum_purchase_quantity'=>'2','maximum_purchase_quantity'=>'1','profit_type'=>'PERCENTAGE','projected_profit_value'=>'10','duration_value'=>'0','duration_unit'=>'DAYS','quantity_decimal_places'=>1]);expect(isset($errors['share_price'],$errors['maximum_purchase_quantity'],$errors['duration_value'],$errors['quantity_decimal_places']));});
test('calculator applies percentage and fixed profit basis without float accounting',function():void{$c=new \App\Services\OfferingCalculator();$base=['currency_code'=>'GBP','share_price_minor'=>2500,'minimum_purchase_quantity'=>'1','maximum_purchase_quantity'=>null,'fractional_shares_allowed'=>0,'quantity_decimal_places'=>0,'duration_value'=>180,'duration_unit'=>'DAYS'];$percent=$c->calculate([...$base,'profit_type'=>'PERCENTAGE','projected_profit_value'=>'12.5'],'10',new DateTimeImmutable('2026-01-01'));expect($percent['investment']->minor===25000&&$percent['projected_profit']->minor===3125&&$percent['maturity_date']->format('Y-m-d')==='2026-06-30');$perShare=$c->calculate([...$base,'profit_type'=>'FIXED','projected_profit_value'=>'5','fixed_profit_basis'=>'PER_SHARE'],'10');expect($perShare['projected_profit']->minor===5000);$perInvestment=$c->calculate([...$base,'profit_type'=>'FIXED','projected_profit_value'=>'50','fixed_profit_basis'=>'PER_INVESTMENT'],'10');expect($perInvestment['projected_profit']->minor===5000);});
test('calculator rejects fractional quantity when offering does not permit it',function():void{$denied=false;try{(new \App\Services\OfferingCalculator())->calculate(['currency_code'=>'USD','share_price_minor'=>100,'minimum_purchase_quantity'=>'1','fractional_shares_allowed'=>0,'quantity_decimal_places'=>0,'profit_type'=>'PERCENTAGE','projected_profit_value'=>'1','duration_value'=>1,'duration_unit'=>'DAYS'],'1.5');}catch(InvalidArgumentException){$denied=true;}expect($denied);});
test('amount-to-quantity conversion uses integer arithmetic',function():void{$c=new \App\Services\OfferingCalculator();$o=['share_price_minor'=>2500,'fractional_shares_allowed'=>1,'quantity_decimal_places'=>3];expect($c->quantityForAmount($o,10000)==='4.000');expect($c->quantityForAmount($o,1250)==='0.500');});
test('exact money supports supported country currencies without float conversion',function():void{expect(Money::parse('10.01','GBP')->minor===1001);expect(Money::parse('999.99','EUR')->minor===99999);expect(Money::parse('5000','JPY',0)->minor===5000);expect(Money::parse('1234.50','PHP')->minor===123450);expect(Money::parse('100.25','TTD')->minor===10025);});
echo "Tests passed. Database migration and seed verification require configured MySQL.\n";
