<?php
declare(strict_types=1);
use App\Controllers\{AdminAiTradingController,AdminCompanyController,AdminContentController,AdminCountryController,AdminFinanceController,AdminInvestmentController,AdminKycController,AdminMethodController,AdminOverviewController,AdminPreviewController,AdminSettingsController,AdminUserController,AdminWithdrawalController};use App\Middleware\{AdminMiddleware,AuthMiddleware};use App\Support\{Response,Router};
/** @var Router $router */
$router->group(['prefix'=>'/admin','as'=>'admin.','middleware'=>[AuthMiddleware::class,AdminMiddleware::class]],function(Router $router):void{
    $router->get('/',[AdminOverviewController::class,'index'],'index');
    $router->get('/companies',[AdminCompanyController::class,'index'],'companies.index');$router->get('/companies/create',[AdminCompanyController::class,'create'],'companies.create');$router->post('/companies',[AdminCompanyController::class,'store'],'companies.store');$router->get('/companies/{company}',[AdminCompanyController::class,'edit'],'companies.edit');$router->post('/companies/{company}',[AdminCompanyController::class,'update'],'companies.update');$router->post('/companies/{company}/archive',[AdminCompanyController::class,'archive'],'companies.archive');
    $router->get('/users',[AdminUserController::class,'index'],'users.index');$router->get('/users/{user}',[AdminUserController::class,'show'],'users.show');$router->post('/users/{user}/country',[AdminUserController::class,'country'],'users.country');$router->post('/users/{user}/status',[AdminUserController::class,'status'],'users.status');$router->post('/users/{user}/popup',[AdminUserController::class,'popup'],'users.popup');$router->post('/users/{user}/popup/{notification}/end',[AdminUserController::class,'endPopup'],'users.popup.end');$router->post('/users/{user}/email',[AdminUserController::class,'email'],'users.email');
    $router->get('/countries',[AdminCountryController::class,'index'],'countries.index');$router->get('/countries/{country}',[AdminCountryController::class,'show'],'countries.show');$router->post('/countries/{country}',[AdminCountryController::class,'update'],'countries.update');$router->post('/countries/{country}/enabled',[AdminCountryController::class,'toggle'],'countries.enabled');$router->post('/countries/{country}/theme',[AdminCountryController::class,'theme'],'countries.theme');$router->post('/countries/{country}/branding',[AdminCountryController::class,'branding'],'countries.branding');$router->post('/countries/{country}/asset',[AdminCountryController::class,'asset'],'countries.asset');$router->post('/countries/{country}/content',[AdminContentController::class,'content'],'countries.content');$router->post('/countries/{country}/legal',[AdminContentController::class,'legal'],'countries.legal');$router->post('/countries/{country}/faq',[AdminContentController::class,'faq'],'countries.faq');$router->post('/countries/{country}/license',[AdminCountryController::class,'license'],'countries.license');$router->post('/countries/{country}/license-settings',[AdminCountryController::class,'licenseSettings'],'countries.license-settings');
    $router->post('/preview/{country}',[AdminPreviewController::class,'start'],'preview.start');$router->post('/preview/stop',[AdminPreviewController::class,'stop'],'preview.stop');
    $router->get('/contact-messages',[AdminContentController::class,'messages'],'contact-messages');$router->post('/contact-messages/{message}',[AdminContentController::class,'messageStatus'],'contact-messages.status');$router->get('/audit-log',[AdminContentController::class,'audit'],'audit');
    $router->get('/settings',[AdminSettingsController::class,'index'],'settings');$router->post('/settings/email-verification',[AdminSettingsController::class,'emailVerification'],'settings.email-verification');
    $router->get('/deposits',[AdminFinanceController::class,'deposits'],'deposits');$router->get('/deposits/{deposit}/files/{file}',[AdminFinanceController::class,'depositFile'],'deposits.file');$router->get('/deposits/{deposit}',[AdminFinanceController::class,'deposit'],'deposits.show');$router->post('/deposits/{deposit}',[AdminFinanceController::class,'depositAction'],'deposits.action');
    $router->get('/transactions',[AdminFinanceController::class,'ledger'],'transactions');$router->post('/transactions/adjust',[AdminFinanceController::class,'adjustment'],'transactions.adjust');
    $router->get('/ai-trading',[AdminAiTradingController::class,'index'],'ai-trading');$router->post('/ai-trading',[AdminAiTradingController::class,'store'],'ai-trading.store');$router->get('/ai-trading/{category}',[AdminAiTradingController::class,'edit'],'ai-trading.edit');$router->post('/ai-trading/{category}',[AdminAiTradingController::class,'update'],'ai-trading.update');
    $router->get('/investments',[AdminInvestmentController::class,'index'],'investments');$router->get('/sale-requests',[AdminInvestmentController::class,'sales'],'sales');$router->post('/sale-requests/{sale}',[AdminInvestmentController::class,'saleAction'],'sales.action');
    $router->get('/kyc',[AdminKycController::class,'index'],'kyc');$router->get('/kyc/configuration',[AdminKycController::class,'config'],'kyc.config');$router->post('/kyc/configuration',[AdminKycController::class,'saveConfig'],'kyc.config.save');$router->get('/kyc/{kyc}/documents/{document}',[AdminKycController::class,'document'],'kyc.document');$router->get('/kyc/{kyc}',[AdminKycController::class,'show'],'kyc.show');$router->post('/kyc/{kyc}',[AdminKycController::class,'action'],'kyc.action');
    $router->get('/withdrawals',[AdminWithdrawalController::class,'index'],'withdrawals');$router->get('/withdrawals/{withdrawal}',[AdminWithdrawalController::class,'show'],'withdrawals.show');$router->post('/withdrawals/{withdrawal}',[AdminWithdrawalController::class,'action'],'withdrawals.action');
    $router->get('/methods/{kind}',[AdminMethodController::class,'methods'],'methods');$router->post('/methods/{kind}',[AdminMethodController::class,'saveMethod'],'methods.save');$router->get('/methods/{kind}/{method}',[AdminMethodController::class,'editMethod'],'methods.edit');$router->post('/methods/{kind}/{method}',[AdminMethodController::class,'updateMethod'],'methods.update');$router->post('/methods/{kind}/{method}/fields',[AdminMethodController::class,'addMethodField'],'methods.fields.add');$router->post('/methods/{kind}/{method}/fields/{field}/delete',[AdminMethodController::class,'deleteMethodField'],'methods.fields.delete');$router->get('/forms',[AdminMethodController::class,'forms'],'forms');$router->post('/forms',[AdminMethodController::class,'saveForm'],'forms.save');$router->post('/forms/fields',[AdminMethodController::class,'addField'],'forms.fields.add');
});
