<?php $marketLabel=$country->isGlobal()?'Investment opportunities':$country->name().' investment opportunities'; ?>
<section class="market-page-hero catalogue-hero">
    <img src="<?= e($media['hero_url']) ?>" alt="<?= e($media['alt']) ?>" loading="eager">
    <div class="market-page-overlay"><p class="eyebrow"><?= e($country->currencyCode()) ?> opportunities</p><h1><?= e($marketLabel) ?></h1><p>Explore companies and compare current investment terms before deciding what deserves a place in your portfolio.</p></div>
</section>
<section class="catalogue-shell">
<form class="catalogue-filters" method="get" action="<?= e(route('companies.index')) ?>">
<label>Search<input name="q" value="<?= e($filters['q']) ?>" placeholder="Company, ticker or industry"></label>
<label>Industry<select name="industry"><option value="">All industries</option><?php foreach($industries as $item):?><option value="<?= e($item['industry']) ?>"<?= $filters['industry']===$item['industry']?' selected':'' ?>><?= e($item['industry']) ?></option><?php endforeach;?></select></label>
<label>Exchange<select name="exchange"><option value="">All exchanges</option><?php foreach($exchanges as $item):?><option value="<?= e($item['stock_exchange']) ?>"<?= $filters['exchange']===$item['stock_exchange']?' selected':'' ?>><?= e($item['stock_exchange']) ?></option><?php endforeach;?></select></label>
<label>Sort<select name="sort"><?php foreach(['featured'=>'Featured','newest'=>'Newest','name'=>'Name','price_low'=>'Price: low to high','price_high'=>'Price: high to low','projected_return'=>'Projected return','duration'=>'Duration'] as $key=>$label):?><option value="<?= e($key) ?>"<?= $filters['sort']===$key?' selected':'' ?>><?= e($label) ?></option><?php endforeach;?></select></label>
<button class="button">Apply</button>
</form>
<?php if(!$companies):?><div class="catalogue-empty"><?php $message='No active investments are available at the moment. New opportunities will appear here when they are ready for review.';require BASE_PATH.'/resources/views/components/empty-state.php';?></div><?php else:?><div class="company-grid professional-grid"><?php foreach($companies as $company):?><article class="company-card professional-company-card"><div class="company-card-visual"><span class="company-mark" aria-hidden="true"><?= e(strtoupper(substr($company['display_name'],0,1))) ?></span><?php if($company['offering_featured']):?><span class="badge featured-badge">Featured</span><?php endif;?></div><div class="company-card-body"><p class="company-meta"><?= e($company['ticker']) ?> · <?= e($company['stock_exchange']) ?></p><h2><?= e($company['display_name']) ?></h2><p class="company-industry"><?= e($company['industry']?:$company['sector']?:'Listed company') ?></p><p class="company-summary"><?= e($company['short_description']?:'Review the company profile and current investment terms.') ?></p><dl class="company-card-facts"><div><dt>Investment price</dt><dd><?= e(country_money(new \App\Support\Money((int)$company['share_price_minor'],$company['currency_code']))) ?></dd></div><div><dt>Projected return</dt><dd><?= e($company['projected_profit_value']) ?><?= $company['profit_type']==='PERCENTAGE'?'%':' fixed' ?></dd></div><div><dt>Duration</dt><dd><?= e($company['duration_value'].' '.strtolower($company['duration_unit'])) ?></dd></div></dl><a class="company-card-cta" href="<?= e(route('companies.show',['company'=>$company['public_id']])) ?>">Review opportunity <span>→</span></a></div></article><?php endforeach;?></div><?php if($pagination->pages()>1):?><nav class="pagination" aria-label="Companies pages"><?php for($i=1;$i<=$pagination->pages();$i++):$query=array_filter([...$filters,'page'=>$i],fn($v)=>$v!=='');?><a<?= $i===$pagination->page?' aria-current="page"':'' ?> href="<?= e(route('companies.index').'?'.http_build_query($query)) ?>"><?= $i ?></a><?php endfor;?></nav><?php endif;?><?php endif;?>
</section>
