<?php $scale=in_array($company['currency_code'],['JPY','KRW'],true)?0:2;$price=country_money(new \App\Support\Money((int)$company['share_price_minor'],$company['currency_code'])); ?>
<section class="company-detail-hero">
    <div class="company-cover"><img src="<?= e($media['hero_url']) ?>" alt="<?= e($media['alt']) ?>" loading="eager"><div class="company-cover-shade"></div><div class="company-mark extra-large" aria-hidden="true"><?= e(strtoupper(substr($company['display_name'],0,1))) ?></div></div>
    <div class="company-hero-copy"><p class="company-meta"><?= e($company['ticker']) ?> · <?= e($company['stock_exchange']) ?></p><h1><?= e($company['display_name']) ?></h1><p class="company-hero-summary"><?= e($company['short_description']?:'Company information and current investment terms.') ?></p><div class="company-hero-price"><span>Investment price</span><strong><?= e($price) ?></strong></div><?php if(!empty($_SESSION['user_id'])): ?><a class="button" href="<?= e(route('companies.buy',['company'=>$company['public_id']])) ?>">Review purchase</a><?php else: ?><a class="button" href="<?= e(route('login')) ?>">Sign in to invest</a><?php endif; ?></div>
</section>
<section class="company-detail-shell">
<div class="company-detail-grid refined-detail-grid">
<section class="detail-panel"><p class="section-label">Company</p><h2>Company overview</h2><p class="detail-prose"><?= nl2br(e($company['long_profile']?:$company['short_description']?:'Company profile is being prepared.')) ?></p><dl class="facts refined-facts"><div><dt>Industry</dt><dd><?= e($company['industry']?:'Not available') ?></dd></div><div><dt>Headquarters</dt><dd><?= e(trim(($company['headquarters_city']?' '.$company['headquarters_city']:'').' '.($company['headquarters_country_code']?:''))?:'Not available') ?></dd></div><div><dt>Founded</dt><dd><?= e($company['year_founded']?:'Not available') ?></dd></div><div><dt>Verified</dt><dd><?= e($company['last_verified_at']?:'Not available') ?></dd></div></dl><?php if($company['website_url']):?><a class="home-inline-link" target="_blank" rel="noopener noreferrer" href="<?= e($company['website_url']) ?>">Visit company website ↗</a><?php endif;?></section>
<aside class="detail-panel calculator refined-calculator" data-offering='<?= e(json_encode(['price_minor'=>(int)$company['share_price_minor'],'currency'=>$company['currency_code'],'scale'=>$scale,'profit_type'=>$company['profit_type'],'profit'=>$company['projected_profit_value'],'fixed_basis'=>$company['fixed_profit_basis'],'min'=>$company['minimum_purchase_quantity'],'max'=>$company['maximum_purchase_quantity'],'fractional'=>(bool)$company['fractional_shares_allowed'],'precision'=>(int)$company['quantity_decimal_places']])) ?>'><p class="section-label">Illustrative calculator</p><h2>Explore the numbers</h2><p class="muted">Projection only. It is not a guarantee of future results.</p><label class="field">Number of shares<input inputmode="decimal" name="quantity" value="<?= e($company['minimum_purchase_quantity']) ?>"></label><dl><div><dt>Investment</dt><dd data-calc="investment">—</dd></div><div><dt>Projected profit</dt><dd data-calc="profit">—</dd></div><div><dt>Projected total</dt><dd data-calc="total">—</dd></div></dl><p data-calc="error" class="form-error" aria-live="polite"></p><?php if(!empty($_SESSION['user_id'])): ?><a class="button" href="<?= e(route('companies.buy',['company'=>$company['public_id']])) ?>">Continue to review</a><?php endif; ?></aside>
</div>
<section class="detail-panel investment-terms-panel"><div class="terms-heading"><p class="section-label">Current terms</p><h2>Investment details</h2></div><dl class="terms-grid"><div><dt>Offering price</dt><dd><?= e($price) ?></dd></div><div><dt>Minimum purchase</dt><dd><?= e($company['minimum_purchase_quantity']) ?> shares</dd></div><div><dt>Projected profit</dt><dd><?= e($company['projected_profit_value']) ?><?= $company['profit_type']==='PERCENTAGE'?'%':' fixed' ?></dd></div><div><dt>Duration</dt><dd><?= e($company['duration_value'].' '.strtolower($company['duration_unit'])) ?></dd></div><div><dt>Share sales</dt><dd><?= $company['selling_enabled']?'Enabled when applicable':'Not currently enabled' ?></dd></div></dl><p class="muted terms-note">Company facts are separate from the investment terms above. Projected results are illustrative and subject to the applicable disclosures.</p></section>
<?php if($sources):?><section class="detail-panel source-panel"><p class="section-label">Research trail</p><h2>Source information</h2><p>Company information is recorded with source references so you can continue your own research.</p><div class="source-links"><?php foreach(array_slice($sources,0,4) as $source):?><a href="<?= e($source['source_url']) ?>" target="_blank" rel="noopener noreferrer"><span><?= e($source['publisher']?:'Source') ?></span><strong><?= e($source['title']) ?></strong><b>↗</b></a><?php endforeach;?></div></section><?php endif;?>
</section>
<script src="<?= e(asset('js/companies.js')) ?>" defer></script>
