<?php
declare(strict_types=1);
use App\Support\Database;
return static function (Database $db): void {
    $db->execute('CREATE TABLE IF NOT EXISTS migrations (migration VARCHAR(190) PRIMARY KEY, batch INT UNSIGNED NOT NULL, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $db->execute("CREATE TABLE IF NOT EXISTS languages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(12) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, native_name VARCHAR(100) NOT NULL, locale VARCHAR(20) NOT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, INDEX(active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS countries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code CHAR(2) NOT NULL UNIQUE, iso3 CHAR(3) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, local_name VARCHAR(150) NOT NULL, currency_code CHAR(3) NOT NULL, currency_symbol VARCHAR(12) NOT NULL, locale VARCHAR(20) NOT NULL, timezone VARCHAR(64) NOT NULL, default_language_id BIGINT UNSIGNED NULL, is_global TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, CONSTRAINT fk_countries_language FOREIGN KEY (default_language_id) REFERENCES languages(id) ON DELETE SET NULL, INDEX(is_active, sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, uuid CHAR(36) NOT NULL UNIQUE, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, country_id BIGINT UNSIGNED NULL, preferred_language_id BIGINT UNSIGNED NULL, account_status ENUM('pending','active','suspended','closed') NOT NULL DEFAULT 'pending', email_verified_at TIMESTAMP NULL, last_login_at TIMESTAMP NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, CONSTRAINT fk_users_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL, CONSTRAINT fk_users_language FOREIGN KEY (preferred_language_id) REFERENCES languages(id) ON DELETE SET NULL, INDEX(account_status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS country_languages (country_id BIGINT UNSIGNED NOT NULL, language_id BIGINT UNSIGNED NOT NULL, is_default TINYINT(1) NOT NULL DEFAULT 0, PRIMARY KEY(country_id, language_id), CONSTRAINT fk_country_languages_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE, CONSTRAINT fk_country_languages_language FOREIGN KEY(language_id) REFERENCES languages(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(150) NOT NULL UNIQUE, setting_value JSON NULL, is_public TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS country_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, country_id BIGINT UNSIGNED NOT NULL, setting_key VARCHAR(150) NOT NULL, setting_value JSON NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, UNIQUE KEY unique_country_setting(country_id, setting_key), CONSTRAINT fk_country_settings_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, channel VARCHAR(30) NOT NULL DEFAULT 'in_app', notification_type VARCHAR(100) NOT NULL, title VARCHAR(190) NOT NULL, body TEXT NULL, data JSON NULL, read_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_notifications_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, read_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, actor_user_id BIGINT UNSIGNED NULL, action VARCHAR(150) NOT NULL, entity_type VARCHAR(150) NOT NULL, entity_id VARCHAR(100) NULL, old_values JSON NULL, new_values JSON NULL, metadata JSON NULL, reason TEXT NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(1000) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_audit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(entity_type, entity_id), INDEX(actor_user_id, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
};
