<?php
declare(strict_types=1);

use App\Support\Database;

return static function (Database $db): void {
    $columns = array_column($db->select('SHOW COLUMNS FROM users'), 'Field');
    if (!in_array('phone', $columns, true)) {
        $db->execute("ALTER TABLE users MODIFY account_status ENUM('pending','active','suspended','restricted','closed') NOT NULL DEFAULT 'active', ADD phone VARCHAR(40) NULL AFTER last_name, ADD country_assignment_source VARCHAR(30) NOT NULL DEFAULT 'REGISTRATION' AFTER assigned_country_id, ADD original_country_id BIGINT UNSIGNED NULL AFTER country_assignment_source, ADD terms_accepted_at TIMESTAMP NULL AFTER last_login_at, ADD terms_version VARCHAR(80) NULL AFTER terms_accepted_at, ADD privacy_accepted_at TIMESTAMP NULL AFTER terms_version, ADD privacy_version VARCHAR(80) NULL AFTER privacy_accepted_at, ADD two_factor_secret_encrypted TEXT NULL AFTER email_verified_at, ADD two_factor_enabled_at TIMESTAMP NULL AFTER two_factor_secret_encrypted, ADD role VARCHAR(30) NOT NULL DEFAULT 'user' AFTER account_status, ADD account_restriction_reason TEXT NULL AFTER role, ADD INDEX(role), ADD INDEX(country_assignment_source), ADD CONSTRAINT fk_users_original_country FOREIGN KEY (original_country_id) REFERENCES countries(id) ON DELETE SET NULL");
    }

    $db->execute("CREATE TABLE IF NOT EXISTS password_reset_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_reset_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS email_verification_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_verification_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS remember_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, selector CHAR(24) NOT NULL UNIQUE, token_hash CHAR(64) NOT NULL, device_label VARCHAR(190) NULL, ip_address VARCHAR(45) NULL, expires_at DATETIME NOT NULL, last_used_at DATETIME NULL, revoked_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_remember_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS user_sessions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, session_hash CHAR(64) NOT NULL UNIQUE, device_label VARCHAR(190) NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(1000) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, last_active_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL, revoked_at DATETIME NULL, CONSTRAINT fk_session_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, revoked_at, expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS security_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, event_type VARCHAR(100) NOT NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(1000) NULL, metadata JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_security_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(user_id, created_at), INDEX(event_type, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS two_factor_recovery_codes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, code_hash CHAR(64) NOT NULL, used_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_recovery_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, UNIQUE KEY unique_user_code(user_id, code_hash), INDEX(user_id, used_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS terms_acceptances (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, document_type VARCHAR(50) NOT NULL, document_version VARCHAR(80) NOT NULL, accepted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ip_address VARCHAR(45) NULL, user_agent VARCHAR(1000) NULL, CONSTRAINT fk_terms_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id, document_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
};
