<?php
declare(strict_types=1);
use App\Support\Database;

return static function (Database $db): void {
    $db->execute("CREATE TABLE IF NOT EXISTS country_branding (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,country_id BIGINT UNSIGNED NOT NULL,brand_name VARCHAR(190) NULL,short_name VARCHAR(100) NULL,logo_asset_id BIGINT UNSIGNED NULL,dark_logo_asset_id BIGINT UNSIGNED NULL,favicon_asset_id BIGINT UNSIGNED NULL,support_email VARCHAR(190) NULL,support_phone VARCHAR(80) NULL,support_whatsapp VARCHAR(80) NULL,business_address TEXT NULL,support_hours VARCHAR(255) NULL,contact_text TEXT NULL,footer_text TEXT NULL,social_links JSON NULL,meta_title VARCHAR(190) NULL,meta_description VARCHAR(300) NULL,updated_at DATETIME NULL,created_at DATETIME NULL,UNIQUE KEY unique_country_branding(country_id),CONSTRAINT fk_branding_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE,CONSTRAINT fk_branding_logo FOREIGN KEY(logo_asset_id) REFERENCES country_assets(id) ON DELETE SET NULL,CONSTRAINT fk_branding_dark_logo FOREIGN KEY(dark_logo_asset_id) REFERENCES country_assets(id) ON DELETE SET NULL,CONSTRAINT fk_branding_favicon FOREIGN KEY(favicon_asset_id) REFERENCES country_assets(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS faqs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,country_id BIGINT UNSIGNED NULL,language_id BIGINT UNSIGNED NOT NULL,category VARCHAR(100) NULL,question VARCHAR(500) NOT NULL,answer TEXT NOT NULL,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NULL,updated_at DATETIME NULL,INDEX(country_id,language_id,is_active,sort_order),CONSTRAINT fk_faq_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE,CONSTRAINT fk_faq_language FOREIGN KEY(language_id) REFERENCES languages(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS legal_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,country_id BIGINT UNSIGNED NOT NULL,language_id BIGINT UNSIGNED NOT NULL,document_type VARCHAR(100) NOT NULL,title VARCHAR(255) NOT NULL,body MEDIUMTEXT NOT NULL,version VARCHAR(80) NOT NULL,is_published TINYINT(1) NOT NULL DEFAULT 0,published_at DATETIME NULL,effective_at DATETIME NULL,created_by_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,UNIQUE KEY unique_legal_version(country_id,language_id,document_type,version),INDEX(country_id,language_id,document_type,is_published,effective_at),CONSTRAINT fk_legal_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE,CONSTRAINT fk_legal_language FOREIGN KEY(language_id) REFERENCES languages(id) ON DELETE CASCADE,CONSTRAINT fk_legal_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS licenses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,country_id BIGINT UNSIGNED NOT NULL,regulator_name VARCHAR(255) NULL,license_name VARCHAR(255) NULL,license_number VARCHAR(255) NULL,issue_date DATE NULL,expiry_date DATE NULL,manual_status VARCHAR(30) NULL,notes TEXT NULL,document_path VARCHAR(255) NULL,original_filename VARCHAR(255) NULL,mime_type VARCHAR(100) NULL,file_size BIGINT UNSIGNED NULL,is_current TINYINT(1) NOT NULL DEFAULT 1,uploaded_at DATETIME NULL,created_by_user_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX(country_id,is_current,expiry_date),CONSTRAINT fk_license_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE,CONSTRAINT fk_license_creator FOREIGN KEY(created_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS country_license_settings (country_id BIGINT UNSIGNED PRIMARY KEY,require_valid_license_for_investing TINYINT(1) NOT NULL DEFAULT 0,expiry_warning_days SMALLINT UNSIGNED NOT NULL DEFAULT 30,updated_at DATETIME NULL,CONSTRAINT fk_country_license_settings FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS contact_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,country_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NULL,name VARCHAR(190) NOT NULL,email VARCHAR(190) NOT NULL,subject VARCHAR(255) NOT NULL,message TEXT NOT NULL,status ENUM('unread','read','resolved','archived') NOT NULL DEFAULT 'unread',ip_address VARCHAR(45) NULL,user_agent VARCHAR(1000) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX(country_id,status,created_at),CONSTRAINT fk_contact_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE RESTRICT,CONSTRAINT fk_contact_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
};
