<?php
declare(strict_types=1);
use App\Support\Database;

return static function (Database $db): void {
    $db->execute("CREATE TABLE IF NOT EXISTS companies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(36) NOT NULL,seed_key VARCHAR(190) NULL,legal_name VARCHAR(255) NOT NULL,display_name VARCHAR(255) NOT NULL,slug VARCHAR(190) NOT NULL,ticker VARCHAR(80) NOT NULL,stock_exchange VARCHAR(190) NOT NULL,exchange_mic VARCHAR(10) NULL,isin VARCHAR(20) NULL,listing_country_code CHAR(2) NULL,headquarters_country_code CHAR(2) NULL,headquarters_city VARCHAR(190) NULL,sector VARCHAR(190) NULL,industry VARCHAR(190) NULL,year_founded SMALLINT UNSIGNED NULL,website_url VARCHAR(500) NULL,investor_relations_url VARCHAR(500) NULL,short_description TEXT NULL,long_profile MEDIUMTEXT NULL,employee_count BIGINT UNSIGNED NULL,market_cap_minor BIGINT NULL,market_cap_currency CHAR(3) NULL,annual_revenue_minor BIGINT NULL,revenue_currency CHAR(3) NULL,revenue_fiscal_year SMALLINT UNSIGNED NULL,last_verified_at DATE NULL,status ENUM('DRAFT','ACTIVE','SUSPENDED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',is_featured TINYINT(1) NOT NULL DEFAULT 0,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,UNIQUE KEY companies_public_id(public_id),UNIQUE KEY companies_slug(slug),UNIQUE KEY companies_seed_key(seed_key),INDEX companies_public(status,is_featured,sort_order),INDEX companies_search(display_name,ticker),INDEX companies_exchange(stock_exchange),INDEX companies_industry(industry)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS company_country_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,country_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY company_country_unique(company_id,country_id),INDEX company_country_country(country_id,company_id),CONSTRAINT fk_company_assignment_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE RESTRICT,CONSTRAINT fk_company_assignment_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS investment_offerings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(36) NOT NULL,company_id BIGINT UNSIGNED NOT NULL,country_id BIGINT UNSIGNED NOT NULL,currency_code CHAR(3) NOT NULL,share_price_minor BIGINT UNSIGNED NOT NULL,minimum_purchase_quantity DECIMAL(20,8) NOT NULL,maximum_purchase_quantity DECIMAL(20,8) NULL,maximum_user_holding DECIMAL(20,8) NULL,total_available_quantity DECIMAL(20,8) NULL,fractional_shares_allowed TINYINT(1) NOT NULL DEFAULT 0,quantity_decimal_places TINYINT UNSIGNED NOT NULL DEFAULT 0,profit_type ENUM('FIXED','PERCENTAGE') NOT NULL,projected_profit_value DECIMAL(20,8) NOT NULL,fixed_profit_basis ENUM('PER_SHARE','PER_INVESTMENT') NULL,duration_value SMALLINT UNSIGNED NOT NULL,duration_unit ENUM('DAYS','WEEKS','MONTHS','YEARS') NOT NULL,selling_enabled TINYINT(1) NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 0,is_featured TINYINT(1) NOT NULL DEFAULT 0,available_from DATETIME NULL,available_until DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,UNIQUE KEY offering_public_id(public_id),UNIQUE KEY offering_company_country(company_id,country_id),INDEX offering_catalogue(country_id,is_active,is_featured,available_from,available_until),INDEX offering_sort_price(country_id,share_price_minor),CONSTRAINT fk_offering_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE RESTRICT,CONSTRAINT fk_offering_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS investment_price_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,offering_id BIGINT UNSIGNED NOT NULL,old_price_minor BIGINT UNSIGNED NULL,new_price_minor BIGINT UNSIGNED NOT NULL,reason VARCHAR(500) NULL,changed_by_user_id BIGINT UNSIGNED NULL,changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX price_history_offering(offering_id,changed_at),CONSTRAINT fk_price_history_offering FOREIGN KEY(offering_id) REFERENCES investment_offerings(id) ON DELETE RESTRICT,CONSTRAINT fk_price_history_actor FOREIGN KEY(changed_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS investment_offering_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,offering_id BIGINT UNSIGNED NOT NULL,changed_by_user_id BIGINT UNSIGNED NULL,changed_fields JSON NOT NULL,reason VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX offering_history_offering(offering_id,created_at),CONSTRAINT fk_offering_history_offering FOREIGN KEY(offering_id) REFERENCES investment_offerings(id) ON DELETE RESTRICT,CONSTRAINT fk_offering_history_actor FOREIGN KEY(changed_by_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS company_sources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,source_type ENUM('OFFICIAL_COMPANY','STOCK_EXCHANGE','REGULATORY','FINANCIAL_DATA','IMAGE','OTHER') NOT NULL,title VARCHAR(255) NOT NULL,source_url VARCHAR(1000) NOT NULL,publisher VARCHAR(255) NULL,notes TEXT NULL,verified_at DATE NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX company_sources_company(company_id,source_type),CONSTRAINT fk_company_source_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS company_images (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,image_type ENUM('LOGO','COVER','GALLERY') NOT NULL,storage_path VARCHAR(255) NOT NULL,original_filename VARCHAR(255) NULL,mime_type VARCHAR(100) NOT NULL,file_size BIGINT UNSIGNED NULL,alt_text VARCHAR(500) NULL,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,is_seeded TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL,INDEX company_images_company(company_id,image_type,sort_order),CONSTRAINT fk_company_image_company FOREIGN KEY(company_id) REFERENCES companies(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS image_sources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_image_id BIGINT UNSIGNED NULL,storage_path VARCHAR(255) NOT NULL,usage_location VARCHAR(255) NOT NULL,source_url VARCHAR(1000) NULL,source_provider VARCHAR(255) NULL,creator VARCHAR(255) NULL,license_name VARCHAR(255) NULL,attribution_text TEXT NULL,downloaded_at DATETIME NULL,notes TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX image_sources_path(storage_path),CONSTRAINT fk_image_source_image FOREIGN KEY(company_image_id) REFERENCES company_images(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
};
