<?php
declare(strict_types=1);

use App\Support\Database;

/** Completes the persisted workflow state that must survive form/method edits. */
return static function (Database $db): void {
    $hasColumn = static function (string $table, string $column) use ($db): bool { return (bool)$db->scalar('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?',[$table,$column]); };
    $db->execute("CREATE TABLE IF NOT EXISTS dynamic_form_snapshots (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, form_id BIGINT UNSIGNED NULL, purpose ENUM('DEPOSIT','WITHDRAWAL','KYC','GENERAL') NOT NULL, definition JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX form_snapshot_form(form_id), CONSTRAINT fk_form_snapshot_form FOREIGN KEY(form_id) REFERENCES dynamic_forms(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if (!$hasColumn('deposit_requests','form_snapshot_id')) $db->execute("ALTER TABLE deposit_requests ADD COLUMN form_snapshot_id BIGINT UNSIGNED NULL AFTER deposit_method_id, ADD CONSTRAINT fk_deposit_form_snapshot FOREIGN KEY(form_snapshot_id) REFERENCES dynamic_form_snapshots(id) ON DELETE SET NULL");
    if (!$hasColumn('kyc_submissions','form_snapshot_id')) $db->execute("ALTER TABLE kyc_submissions ADD COLUMN form_snapshot_id BIGINT UNSIGNED NULL AFTER configuration_version, ADD CONSTRAINT fk_kyc_form_snapshot FOREIGN KEY(form_snapshot_id) REFERENCES dynamic_form_snapshots(id) ON DELETE SET NULL");
    if (!$hasColumn('withdrawal_requests','form_snapshot_id')) $db->execute("ALTER TABLE withdrawal_requests ADD COLUMN form_snapshot_id BIGINT UNSIGNED NULL AFTER withdrawal_method_id, ADD CONSTRAINT fk_withdrawal_form_snapshot FOREIGN KEY(form_snapshot_id) REFERENCES dynamic_form_snapshots(id) ON DELETE SET NULL");
    $db->execute("CREATE TABLE IF NOT EXISTS withdrawal_submission_values (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, withdrawal_request_id BIGINT UNSIGNED NOT NULL, field_key VARCHAR(100) NOT NULL, field_label VARCHAR(255) NOT NULL, value_text TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY withdrawal_field(withdrawal_request_id,field_key), CONSTRAINT fk_withdrawal_value_request FOREIGN KEY(withdrawal_request_id) REFERENCES withdrawal_requests(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS saved_withdrawal_accounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id CHAR(36) NOT NULL, user_id BIGINT UNSIGNED NOT NULL, withdrawal_method_id BIGINT UNSIGNED NOT NULL, nickname VARCHAR(100) NOT NULL, values_encrypted MEDIUMTEXT NOT NULL, masked_summary VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, last_used_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL, UNIQUE KEY saved_withdrawal_account_public(public_id), INDEX saved_withdrawal_user(user_id,is_active), CONSTRAINT fk_saved_withdrawal_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT fk_saved_withdrawal_method FOREIGN KEY(withdrawal_method_id) REFERENCES withdrawal_methods(id) ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS email_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, template_key VARCHAR(100) NOT NULL, country_id BIGINT UNSIGNED NULL, language_code VARCHAR(12) NULL, subject_template VARCHAR(255) NOT NULL, html_template MEDIUMTEXT NOT NULL, text_template TEXT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NULL, UNIQUE KEY email_template_variant(template_key,country_id,language_code), CONSTRAINT fk_email_template_country FOREIGN KEY(country_id) REFERENCES countries(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    $db->execute("CREATE TABLE IF NOT EXISTS email_delivery_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, template_key VARCHAR(100) NOT NULL, recipient VARCHAR(255) NOT NULL, delivery_status ENUM('SENT','FAILED','LOGGED') NOT NULL, related_entity_type VARCHAR(80) NULL, related_entity_id VARCHAR(80) NULL, failure_reason VARCHAR(500) NULL, sent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX email_delivery_user(user_id,created_at), INDEX email_delivery_status(delivery_status,created_at), CONSTRAINT fk_email_delivery_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    if (!$hasColumn('withdrawal_methods','fee_behavior')) $db->execute("ALTER TABLE withdrawal_methods ADD COLUMN fee_behavior ENUM('DEDUCT_FROM_REQUEST','ADD_TO_DEBIT') NOT NULL DEFAULT 'DEDUCT_FROM_REQUEST' AFTER fee_value");
    /* Compatibility alias used by the purchase service while preserving the original offering column. */
    if (!$hasColumn('investment_offerings','total_available_shares')) $db->execute("ALTER TABLE investment_offerings ADD COLUMN total_available_shares DECIMAL(20,8) GENERATED ALWAYS AS (total_available_quantity) STORED AFTER total_available_quantity");
};
