<div class="dashboard-page-head"><div><p class="eyebrow">AI trading administration</p><h1>AI trading codes</h1><p class="muted">Create global categories priced in USD. Every new category receives 50 unique codes automatically, and another 50 are generated whenever available stock reaches zero.</p></div></div>
<div class="grid two dashboard-split">
<section class="card">
<p class="section-label">Create category</p><h2>New AI trading category</h2>
<form method="post" action="<?= e(route('admin.ai-trading.store')) ?>" class="form-stack"><?= app('csrf')->input() ?>
<label class="field">Category name<input name="name" required placeholder="Beginner"></label>
<label class="field">Description<textarea name="description" rows="4" placeholder="Describe this AI trading category."></textarea></label>
<div class="form-grid"><label class="field">Price in USD<input name="price_usd" inputmode="decimal" required placeholder="100.00"></label><label class="field">Fixed profit %<input name="profit_percent" inputmode="decimal" required placeholder="50"></label></div>
<div class="form-grid"><label class="field">Duration<input name="duration_value" type="number" min="1" required value="30"></label><label class="field">Duration unit<select name="duration_unit"><option value="HOURS">Hours</option><option value="DAYS" selected>Days</option><option value="WEEKS">Weeks</option><option value="MONTHS">Months</option></select></label></div>
<button class="button" type="submit">Create category + 50 codes</button>
</form>
</section>
<section class="card"><p class="section-label">Pricing rule</p><h2>Global catalogue, frozen FX</h2><p>Categories are configured once in USD and shown to every country. Non-USD prices use the build-time FX snapshot dated <strong><?= e(config('ai_trading.fx_snapshot_date')) ?></strong>.</p><p>Each user purchase permanently stores the exact FX rate, local price, profit amount and maturity payout used at checkout.</p></section>
</div>
<section class="card"><p class="section-label">Categories</p><h2>Current AI trading categories</h2><div class="table-wrap"><table><thead><tr><th>Category</th><th>USD price</th><th>Profit</th><th>Duration</th><th>Available</th><th>Sold</th><th>Active</th><th>Completed</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($categories as $c): ?><tr><td><strong><?= e($c['name']) ?></strong></td><td>$<?= e(number_format((int)$c['price_usd_minor']/100,2)) ?></td><td><?= e(rtrim(rtrim((string)$c['profit_percent'],'0'),'.')) ?>%</td><td><?= e($c['duration_value'].' '.strtolower($c['duration_unit'])) ?></td><td><?= e((int)$c['available_codes']) ?></td><td><?= e((int)$c['sold_codes']) ?></td><td><?= e((int)$c['active_codes']) ?></td><td><?= e((int)$c['completed_codes']) ?></td><td><?= $c['is_active']?'Active':'Disabled' ?></td><td><a href="<?= e(route('admin.ai-trading.edit',['category'=>$c['public_id']])) ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="card"><p class="section-label">Recent purchases</p><h2>AI trading activity</h2><div class="table-wrap"><table><thead><tr><th>Reference</th><th>User</th><th>Category</th><th>Currency</th><th>Purchase</th><th>Profit</th><th>Status</th><th>Purchased</th><th>Completion</th></tr></thead><tbody><?php foreach($purchases as $p): ?><tr><td><?= e($p['reference']) ?></td><td><?= e($p['email']) ?></td><td><?= e($p['category_name']) ?></td><td><?= e($p['currency_code']) ?></td><td><?= e($p['purchase_amount_minor']) ?></td><td><?= e($p['profit_amount_minor']) ?></td><td><?= e($p['status']) ?></td><td><?= e($p['purchased_at']) ?></td><td><?= e($p['matures_at']?:'Not activated') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
