<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Support\{Request,Response};
final class AdminContentController extends Controller {
    public function content(Request $r):Response{$country=$this->country($r);$lang=(int)$r->input('language_id');app('content')->save((int)$country['id'],$lang,(string)$r->input('page_key','home'),$r->all());app('audit')->record((int)$_SESSION['user_id'],'country.content_changed','country',(int)$country['id'],null,['page'=>$r->input('page_key')],null,$r);$this->flash('success','Content saved.');return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}
    public function legal(Request $r):Response{$country=$this->country($r);try{$id=app('legal')->save((int)$country['id'],(int)$r->input('language_id'),(string)$r->input('document_type'),$r->all(),(int)$_SESSION['user_id']);app('audit')->record((int)$_SESSION['user_id'],'legal.version_created','legal_document',$id,null,['country'=>$country['id'],'type'=>$r->input('document_type')],null,$r);$this->flash('success','New legal document version created.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}
    public function faq(Request $r):Response{$country=$this->country($r);$d=$r->all();$d['country_id']=$country['id'];$d['language_id']=(int)$d['language_id'];$d['sort_order']=(int)($d['sort_order']??0);app('faqs')->save($d);app('audit')->record((int)$_SESSION['user_id'],'faq.created','faq',null,null,['country'=>$country['id']],null,$r);$this->flash('success','FAQ saved.');return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}
    public function messages(Request $r):Response{return $this->view('admin.contact-messages',['title'=>'Contact messages','messages'=>app('contacts')->list((string)$r->input('status',''))],'layouts.admin');}public function messageStatus(Request $r):Response{app('contacts')->setStatus((int)$r->route('message'),(string)$r->input('status'));app('audit')->record((int)$_SESSION['user_id'],'contact.status_changed','contact_message',$r->route('message'),null,['status'=>$r->input('status')],null,$r);return Response::redirect(route('admin.contact-messages'));}
    public function audit(Request $r):Response{$db=app('database');$rows=$db?$db->select('SELECT a.*,u.email actor_email FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_user_id ORDER BY a.created_at DESC LIMIT 150'):[];return $this->view('admin.audit',['title'=>'Audit log','entries'=>$rows],'layouts.admin');}
    private function country(Request $r):array{$country=app('countries')->byId((int)$r->route('country'));if(!$country)throw new \RuntimeException('Country not found.');return $country;}
}
