<?php
declare(strict_types=1);namespace App\Controllers;use App\Support\{Request,Response};
/** Small server-side method/form builder; field definitions remain database-owned. */
final class AdminMethodController extends Controller {
 public function methods(Request $r):Response{$kind=(string)$r->route('kind');$table=$kind==='withdrawal'?'withdrawal_methods':'deposit_methods';$rows=app('database')?->select('SELECT * FROM '.$table.' ORDER BY sort_order,name')??[];return $this->view('admin/methods',['title'=>ucfirst($kind).' methods','kind'=>$kind,'methods'=>$rows,'countries'=>app('countries')->all()],'layouts.admin');}
 public function saveMethod(Request $r):Response{try{$kind=(string)$r->route('kind');if(!in_array($kind,['deposit','withdrawal'],true))throw new \InvalidArgumentException('Unknown method type.');$db=app('database');$table=$kind==='withdrawal'?'withdrawal_methods':'deposit_methods';$slug=strtolower(trim((string)$r->input('slug')));if(!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/',$slug))throw new \InvalidArgumentException('Use a safe URL slug.');$db?->transaction(function($db)use($r,$kind,$table,$slug){$db->execute('INSERT INTO '.$table.'(public_id,name,slug,description,instructions,enabled,minimum_amount_minor,maximum_amount_minor,fee_type,fee_value,estimated_processing_time,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[bin2hex(random_bytes(16)),trim((string)$r->input('name')), $slug,trim((string)$r->input('description')),trim((string)$r->input('instructions')), $r->input('enabled')?1:0,(int)$r->input('minimum_amount_minor',0),$r->input('maximum_amount_minor')!==''?(int)$r->input('maximum_amount_minor'):null,$r->input('fee_type','NONE'),$r->input('fee_value','0'),trim((string)$r->input('processing_time')),0]);$id=(int)$db->pdo()->lastInsertId();$pivot=$kind==='withdrawal'?'withdrawal_method_countries':'deposit_method_countries';foreach((array)$r->input('countries',[]) as $countryId)$db->execute('INSERT INTO '.$pivot.' VALUES (?,?)',[$id,(int)$countryId]);});$this->flash('success','Method created. Add fields in the form builder next.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('admin.methods',['kind'=>(string)$r->route('kind')]);}
 public function forms(Request $r):Response{$forms=app('database')?->select('SELECT * FROM dynamic_forms ORDER BY purpose,name')??[];return $this->view('admin/forms',['title'=>'Dynamic form builder','forms'=>$forms],'layouts.admin');}
 public function saveForm(Request $r):Response{try{$db=app('database');$purpose=(string)$r->input('purpose');if(!in_array($purpose,['DEPOSIT','WITHDRAWAL','KYC','GENERAL'],true))throw new \InvalidArgumentException('Invalid form purpose.');$key=strtolower(preg_replace('/[^a-z0-9_]+/','_',trim((string)$r->input('form_key')))??'');$db?->execute('INSERT INTO dynamic_forms(name,form_key,purpose,active) VALUES (?,?,?,1)',[trim((string)$r->input('name')),$key,$purpose]);$this->flash('success','Form created.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('admin.forms');}
 public function addField(Request $r):Response{try{$type=(string)$r->input('field_type');$allowed=['TEXT','NUMBER','EMAIL','PHONE','TEXTAREA','SELECT','MULTI_SELECT','RADIO','CHECKBOX','DATE','FILE','COPYABLE_VALUE','INSTRUCTION'];if(!in_array($type,$allowed,true))throw new \InvalidArgumentException('Invalid field type.');$key=strtolower(preg_replace('/[^a-z0-9_]+/','_',trim((string)$r->input('field_key')))??'');app('database')?->execute('INSERT INTO dynamic_form_fields(form_id,field_key,field_type,label,placeholder,help_text,is_required,sort_order) VALUES (?,?,?,?,?,?,?,?)',[(int)$r->input('form_id'),$key,$type,trim((string)$r->input('label')),trim((string)$r->input('placeholder')),trim((string)$r->input('help_text')),$r->input('required')?1:0,(int)$r->input('sort_order',0)]);$this->flash('success','Field added.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('admin.forms');}
}
