<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Support\{Request,Response};
final class AdminCountryController extends Controller {
    public function index(Request $r):Response{return $this->view('admin.countries',['title'=>'Country Packs','countries'=>app('countries')->all(),'allCountries'=>app('countries')->all()],'layouts.admin');}
    public function show(Request $r):Response{$country=app('countries')->byId((int)$r->route('country'));if(!$country)return new Response('Not found',404);return $this->view('admin.country-edit',['title'=>$country['name'],'country'=>$country,'languages'=>app('countries')->languages($country),'branding'=>app('branding')->forCountry($country),'license'=>app('licenses')->current((int)$country['id']),'licenseSettings'=>app('licenses')->settings((int)$country['id']),'legal'=>app('legal')->list((int)$country['id']),'faqs'=>app('faqs')->list((int)$country['id'])],'layouts.admin');}
    public function update(Request $r):Response{$country=$this->country($r);$data=$r->all();app('country_admin')->update((int)$country['id'],['name'=>trim($data['name']),'local_name'=>trim($data['local_name']),'currency_code'=>strtoupper(trim($data['currency_code'])),'currency_symbol'=>trim($data['currency_symbol']),'currency_symbol_position'=>$data['currency_symbol_position']==='after'?'after':'before','locale'=>trim($data['locale']),'timezone'=>trim($data['timezone']),'default_language_id'=>(int)$data['default_language_id'],'sort_order'=>(int)$data['sort_order']]);$this->audit('country.updated',$country,['name'=>$country['name']],['name'=>$data['name']],$r);return $this->ok('Country settings saved.',$country);}
    public function toggle(Request $r):Response{$country=$this->country($r);try{app('country_admin')->enabled((int)$country['id'],!empty($r->input('enabled')));$this->audit('country.enabled_changed',$country,['enabled'=>$country['is_enabled']],['enabled'=>!empty($r->input('enabled'))],$r);return $this->ok('Country availability updated.',$country);}catch(\DomainException $e){$this->flash('error',$e->getMessage());return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}}
    public function theme(Request $r):Response{$country=$this->country($r);app('country_admin')->theme((int)$country['id'],$r->all());$this->audit('country.theme_changed',$country,null,['theme'=>'updated'],$r);return $this->ok('Theme saved.',$country);}
    public function branding(Request $r):Response{$country=$this->country($r);$d=$r->all();$links=[];foreach(['facebook','instagram','linkedin','x','youtube','telegram']as$key)if(!empty($d['social_'.$key])){$url=trim($d['social_'.$key]);if(filter_var($url,FILTER_VALIDATE_URL))$links[$key]=$url;}app('branding')->save((int)$country['id'],array_merge($d,['social_links'=>$links]));$this->audit('country.branding_changed',$country,null,['branding'=>'updated'],$r);return $this->ok('Branding saved.',$country);}
    public function asset(Request $r):Response{$country=$this->country($r);try{$id=app('country_admin')->attachAsset((int)$country['id'],(string)$r->input('asset_type'),$r->file('asset')??[],(string)$r->input('alt_text',''));$this->audit('country.asset_uploaded',$country,null,['asset_id'=>$id,'type'=>$r->input('asset_type')],$r);return $this->ok('Image uploaded.',$country);}catch(\Throwable $e){$this->flash('error',$e->getMessage());return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}}
    public function license(Request $r):Response{$country=$this->country($r);try{$id=app('licenses')->save((int)$country['id'],$r->all(),$r->file('document'),(int)$_SESSION['user_id']);$this->audit('license.replaced',$country,null,['license_id'=>$id],$r);return $this->ok('License record saved.',$country);}catch(\Throwable $e){$this->flash('error',$e->getMessage());return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}}
    public function licenseSettings(Request $r):Response{$country=$this->country($r);app('licenses')->saveSettings((int)$country['id'],!empty($r->input('require_valid_license_for_investing')),(int)$r->input('expiry_warning_days',30));$this->audit('license.settings_changed',$country,null,['required'=>!empty($r->input('require_valid_license_for_investing'))],$r);return $this->ok('License requirements saved.',$country);}
    private function country(Request $r):array{$country=app('countries')->byId((int)$r->route('country'));if(!$country)throw new \RuntimeException('Country not found.');return $country;}private function audit(string $action,array $country,?array $old,?array $new,Request $r):void{app('audit')->record((int)$_SESSION['user_id'],$action,'country',(int)$country['id'],$old,$new,null,$r);}private function ok(string $m,array $country):Response{$this->flash('success',$m);return Response::redirect(route('admin.countries.show',['country'=>$country['id']]));}
}
