<?php
declare(strict_types=1);namespace App\Controllers;use App\Exceptions\NotFoundException;use App\Support\{Money,Request,Response};
final class AdminFinanceController extends Controller {private function minor(Request $r):int{$currency=(string)$r->input('currency',country()->currencyCode());return Money::parse((string)$r->input('amount'),$currency,in_array($currency,['JPY','KRW'],true)?0:2)->minor;}
 public function deposits(Request $r):Response{$data=app('deposits')->queue($r->all(),max(1,(int)$r->input('page',1)));return $this->view('admin/deposits',['title'=>'Deposits','deposits'=>$data['items'],'filters'=>$r->all()],'layouts.admin');}
 public function deposit(Request $r):Response{$d=app('database')?->one('SELECT d.*,u.email,u.first_name,u.last_name,m.name method_name FROM deposit_requests d JOIN users u ON u.id=d.user_id JOIN deposit_methods m ON m.id=d.deposit_method_id WHERE d.id=?',[(int)$r->route('deposit')]);if(!$d)throw new NotFoundException('Deposit not found.');return $this->view('admin/deposit-detail',['title'=>'Deposit '.$d['reference'],'deposit'=>$d,'values'=>app('deposits')->values((int)$d['id']),'files'=>app('database')?->select('SELECT * FROM deposit_files WHERE deposit_request_id=?',[$d['id']])??[]],'layouts.admin');}
 public function depositFile(Request $r):Response{$file=app('database')?->one('SELECT * FROM deposit_files WHERE id=? AND deposit_request_id=?',[(int)$r->route('file'),(int)$r->route('deposit')]);if(!$file)throw new NotFoundException('Receipt not found.');return app(MediaController::class)->privateFile((string)$file['storage_path'],(string)$file['original_filename'],(string)$file['mime_type'],(bool)$r->input('download'));}
 public function depositAction(Request $r):Response{try{$id=(int)$r->route('deposit');$action=(string)$r->input('action');if($action==='review')app('deposits')->review($id,(int)$_SESSION['user_id']);elseif($action==='approve')app('deposits')->approve($id,(int)$_SESSION['user_id'],(string)$r->input('notes',''));elseif($action==='reject')app('deposits')->reject($id,(int)$_SESSION['user_id'],(string)$r->input('reason'));else throw new \InvalidArgumentException('Unknown action.');$this->flash('success','Deposit updated.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('admin.deposits.show',['deposit'=>(int)$r->route('deposit')]);}
 public function ledger(Request $r):Response{$db=app('database');$rows=$db?->select('SELECT l.*,u.email FROM ledger_transactions l JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT 100')??[];return $this->view('admin/ledger',['title'=>'Ledger transactions','transactions'=>$rows],'layouts.admin');}
 public function adjustment(Request $r):Response{try{$user=app('users')->find((int)$r->input('user_id'));if(!$user)throw new \RuntimeException('User not found.');$country=app('countries')->byId((int)$user['country_id'])??country()->country;$wallet=app('wallets')->walletFor($user,$country);$direction=(string)$r->input('direction');$reason=trim((string)$r->input('reason'));if(!in_array($direction,['CREDIT','DEBIT'],true)||$reason==='')throw new \InvalidArgumentException('Direction and reason are required.');app('wallets')->move((int)$wallet['id'],$direction==='CREDIT'?'ADMIN_CREDIT':'ADMIN_DEBIT',$direction,$this->minor($r),'Manual administrator adjustment','admin-adjustment',(string)bin2hex(random_bytes(8)),(int)$_SESSION['user_id'],$reason);app('audit')->record((int)$_SESSION['user_id'],'wallet.manual_'.$direction,'wallet',(int)$wallet['id'],null,['reason'=>$reason],$reason,$r);$this->flash('success','Wallet adjustment recorded.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('admin.transactions');}}
