<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Support\{Request,Response}; use App\Validation\Validator;
final class AuthController extends Controller {
    public function login(Request $request): Response { return $this->view('auth.login',['title'=>__('auth.login')],'layouts.auth'); }
    public function authenticate(Request $request): Response { if(!$this->loginRateAllowed($request))return $this->back('login','Too many sign-in attempts. Please wait a few minutes.'); $data=$request->all();$v=new Validator($data);$v->validate(['email'=>'required|max:190','password'=>'required']);if($v->fails())return $this->validationBack('login',$v->errors());$result=app('auth')->attempt((string)$data['email'],(string)$data['password'],!empty($data['remember']),$request);if($result['status']==='invalid')return $this->back('login',__('auth.invalid_credentials'));if($result['status']==='blocked')return $this->back('login','This account is not currently available.');if($result['status']==='two_factor')return Response::redirect(route('two-factor.challenge'));return Response::redirect($this->intended()); }
    public function register(Request $request): Response { return $this->view('auth.register',['title'=>__('auth.register')],'layouts.auth'); }
    public function store(Request $request): Response { $data=$request->all();$v=new Validator($data);$v->validate(['first_name'=>'required|max:100','last_name'=>'required|max:100','email'=>'required|email|max:190','phone'=>'optional|max:40','password'=>'required|strong_password|confirmed','terms'=>'required|accepted','privacy'=>'required|accepted']);if($v->fails())return $this->validationBack('register',$v->errors());try{$user=app('auth')->register($data,$request);if(app('settings')->bool('require_email_verification'))app('email_verification')->send($user);app('auth')->complete($user,$request,false);$this->flash('success','Your account is ready.');return Response::redirect(route('dashboard.index'));}catch(\DomainException $e){return $this->back('register',$e->getMessage());} }
    public function logout(Request $request): Response { app('sessions')->logout($request);return Response::redirect(route('home')); }
    public function verify(Request $request): Response { return $this->view('auth.verify-email',['title'=>'Verify email address','token'=>(string)$request->input('token','')],'layouts.auth'); }
    public function confirmVerification(Request $request): Response { $ok=app('email_verification')->verify((string)$request->input('token',''));$this->flash($ok?'success':'error',$ok?'Your email address has been verified.':'This verification link is invalid or has expired.');return Response::redirect(!empty($_SESSION['user_id'])?route('dashboard.security'):route('login')); }
    public function resendVerification(Request $request): Response { $user=app('users')->find((int)$_SESSION['user_id']);if($user)app('email_verification')->send($user);$this->flash('success','If needed, a verification email has been sent.');return Response::redirect(route('dashboard.security')); }
    private function intended(): string { $path=(string)($_SESSION['intended_url']??'');unset($_SESSION['intended_url']); return str_starts_with($path,'/')&&!str_starts_with($path,'//')?$path:route('dashboard.index'); }
    private function loginRateAllowed(Request $request): bool { $key='login-rate:'.$request->ip().':'.hash('sha256',strtolower((string)$request->input('email','')));$cache=app('cache');$count=(int)$cache->get($key,0);if($count>=8)return false;$cache->put($key,$count+1,600);return true; }
    private function validationBack(string $route,array $errors): Response { $_SESSION['_errors']=$errors;$_SESSION['_old']=$_POST;return Response::redirect(route($route)); }
    private function back(string $route,string $message): Response { $this->flash('error',$message);return Response::redirect(route($route)); }
}
