<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Exceptions\NotFoundException;use App\Support\{Money,Request,Response};

final class FinancialController extends Controller {
 private function user():array{return app('users')->find((int)$_SESSION['user_id']);}
 private function minor(Request $r,string $key):int{$c=country();$scale=in_array($c->currencyCode(),['JPY','KRW'],true)?0:2;return Money::parse((string)$r->input($key,''),$c->currencyCode(),$scale)->minor;}
 public function deposit(Request $r):Response{$u=$this->user();$methods=app('deposits')->methods(country()->id());$selected=(int)$r->input('method',0);$method=$selected?app('deposits')->method(country()->id(),$selected):null;return $this->view('financial.deposit',['title'=>'Deposit funds','methods'=>$methods,'method'=>$method,'wallet'=>app('wallets')->walletFor($u,country()->country)],'layouts.dashboard');}
 public function reviewDeposit(Request $r):Response{try{$amountInput=trim((string)$r->input('amount',''));$amount=$this->minor($r,'amount');$quote=app('deposits')->quote(country()->country,(int)$r->input('method_id'),$amount);$method=$quote['method'];$details=[];$qr=null;if(!empty($method['payment_details'])){$decoded=json_decode((string)$method['payment_details'],true);$details=is_array($decoded)?$decoded:[];}if(($method['method_type']??'')==='CRYPTO'&&!empty($details['wallet_address']))$qr=app('qr')->dataUri((string)$details['wallet_address']);return $this->view('financial.deposit-review',['title'=>'Complete deposit payment','method'=>$method,'quote'=>$quote,'amountInput'=>$amountInput,'fields'=>app('forms')->definition($method['form_id']?(int)$method['form_id']:null),'paymentDetails'=>$details,'methodQr'=>$qr],'layouts.dashboard');}catch(\Throwable $e){$this->flash('error',$e->getMessage());return $this->redirect('dashboard.deposit');}}
 public function submitDeposit(Request $r):Response{try{$result=app('deposits')->submit($this->user(),country()->country,(int)$r->input('method_id'),$this->minor($r,'amount'),$r->all(),$r->files());app('deposits')->attachFiles((int)$result['id'],$r->files());$this->flash('success','Deposit request submitted. Reference: '.$result['reference']);return $this->redirect('dashboard.deposit.detail',['deposit'=>$result['reference']]);}catch(\Throwable $e){$this->flash('error',$e->getMessage());return $this->reviewDeposit($r);}}
 public function deposits(Request $r):Response{$data=app('deposits')->forUser((int)$this->user()['id'],max(1,(int)$r->input('page',1)));return $this->view('financial.deposits',['title'=>'Deposit history','deposits'=>$data['items'],'total'=>$data['total']],'layouts.dashboard');}
 public function depositDetail(Request $r):Response{$d=app('deposits')->findForUser((int)$this->user()['id'],(string)$r->route('deposit'));if(!$d)throw new NotFoundException('Deposit request not found.');return $this->view('financial.deposit-detail',['title'=>'Deposit '.$d['reference'],'deposit'=>$d,'values'=>app('deposits')->values((int)$d['id']),'files'=>app('database')?->select('SELECT id,original_filename FROM deposit_files WHERE deposit_request_id=?',[$d['id']])??[]],'layouts.dashboard');}
 public function depositFile(Request $r):Response{$file=app('database')?->one('SELECT f.*,d.user_id FROM deposit_files f JOIN deposit_requests d ON d.id=f.deposit_request_id WHERE f.id=? AND d.reference=?',[(int)$r->route('file'),(string)$r->route('deposit')]);if(!$file||(int)$file['user_id']!==(int)$this->user()['id'])throw new NotFoundException('Receipt not found.');return app(MediaController::class)->privateFile((string)$file['storage_path'],(string)$file['original_filename'],(string)$file['mime_type'],(bool)$r->input('download'));}
 public function cancelDeposit(Request $r):Response{try{app('deposits')->cancel((int)$this->user()['id'],(string)$r->route('deposit'));$this->flash('success','Deposit request cancelled.');}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('dashboard.deposits');}
 public function transactions(Request $r):Response{$data=app('wallets')->history((int)$this->user()['id'],$r->all(),max(1,(int)$r->input('page',1)));return $this->view('financial.transactions',['title'=>'Transactions','transactions'=>$data['items'],'filters'=>$r->all(),'total'=>$data['total']],'layouts.dashboard');}
 public function transaction(Request $r):Response{$row=app('database')?->one('SELECT * FROM ledger_transactions WHERE user_id=? AND reference=?',[(int)$this->user()['id'],(string)$r->route('transaction')]);if(!$row)throw new NotFoundException('Transaction not found.');return $this->view('financial.transaction-detail',['title'=>'Transaction '.$row['reference'],'transaction'=>$row],'layouts.dashboard');}
}
