<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Exceptions\NotFoundException;use App\Support\{Request,Response};
final class InvestmentController extends Controller {
 private function user():array{return app('users')->find((int)$_SESSION['user_id']);}
 public function buy(Request $r):Response{$company=app('companies')->company(country(),(string)$r->route('company'));if(!$company)throw new NotFoundException('Investment opportunity not found.');return $this->view('investments.buy',['title'=>'Buy '.$company['display_name'],'company'=>$company,'wallet'=>app('wallets')->walletFor($this->user(),country()->country)],'layouts.dashboard');}
 public function review(Request $r):Response{try{$company=app('companies')->company(country(),(string)$r->route('company'));if(!$company)throw new NotFoundException('Investment opportunity not found.');$quantity=(string)$r->input('quantity','');if($quantity==='')$quantity=app('offering_calculator')->quantityForAmount($company,(int)\App\Support\Money::parse((string)$r->input('amount'),country()->currencyCode(),in_array(country()->currencyCode(),['JPY','KRW'],true)?0:2)->minor);$quote=app('investments')->quote($this->user(),country()->country,(int)$company['offering_id'],$quantity);$_SESSION['purchase_review']=['company'=>$company['public_id'],'quantity'=>$quantity,'token'=>bin2hex(random_bytes(16))];return $this->view('investments.review',['title'=>'Review investment','company'=>$company,'quantity'=>$quantity,'quote'=>$quote['quote'],'wallet'=>app('wallets')->walletFor($this->user(),country()->country),'token'=>$_SESSION['purchase_review']['token']],'layouts.dashboard');}catch(\Throwable $e){$this->flash('error',$e->getMessage());return $this->redirect('companies.show',['company'=>(string)$r->route('company')]);}}
 public function confirm(Request $r):Response{$review=$_SESSION['purchase_review']??[];if(!$review||!hash_equals((string)$review['token'],(string)$r->input('purchase_token','')))throw new \RuntimeException('Purchase confirmation expired.');$company=app('companies')->company(country(),(string)$review['company']);if(!$company)throw new NotFoundException('Investment opportunity not found.');try{$position=app('investments')->purchase($this->user(),country()->country,(int)$company['offering_id'],(string)$review['quantity'],(string)$review['token']);unset($_SESSION['purchase_review']);return $this->view('investments.success',['title'=>'Investment purchased','investment'=>$position,'company'=>$company],'layouts.dashboard');}catch(\Throwable $e){$this->flash('error',$e->getMessage());return $this->redirect('companies.show',['company'=>$company['public_id']]);}}
 public function index(Request $r):Response{return $this->view('investments.index',['title'=>'Investments','investments'=>app('investments')->forUser((int)$this->user()['id'],$r->all())],'layouts.dashboard');}
 public function portfolio(Request $r):Response{$user=$this->user();return $this->view('investments.portfolio',['title'=>'Portfolio','summary'=>app('investments')->portfolio((int)$user['id']),'investments'=>app('investments')->forUser((int)$user['id']),'wallet'=>app('wallets')->walletFor($user,country()->country)],'layouts.dashboard');}
 public function show(Request $r):Response{$i=app('investments')->findForUser((int)$this->user()['id'],(string)$r->route('investment'));if(!$i)throw new NotFoundException('Investment not found.');return $this->view('investments.show',['title'=>'Investment '.$i['public_id'],'investment'=>$i],'layouts.dashboard');}
 public function sale(Request $r):Response{try{$sale=app('investments')->requestSale($this->user(),country()->country,(string)$r->route('investment'));$this->flash('success','Sale request submitted: '.$sale['reference']);}catch(\Throwable $e){$this->flash('error',$e->getMessage());}return $this->redirect('dashboard.investments.show',['investment'=>(string)$r->route('investment')]);}
}
