<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Security\PasswordHasher; use App\Support\{Request,Response};use App\Validation\Validator;
final class PasswordController extends Controller {
    public function forgot(Request $request): Response{return $this->view('auth.forgot-password',['title'=>'Reset password'],'layouts.auth');}
    public function sendReset(Request $request): Response{$email=strtolower(trim((string)$request->input('email','')));if(filter_var($email,FILTER_VALIDATE_EMAIL))try{app('password_resets')->request($email);}catch(\Throwable $e){app('logger')->error('Password reset email failed',['message'=>$e->getMessage()]);}$this->flash('success','If an account exists for that email, password reset instructions have been sent.');return Response::redirect(route('forgot-password'));}
    public function reset(Request $request): Response{return $this->view('auth.reset-password',['title'=>'Choose a new password','token'=>(string)$request->input('token','')],'layouts.auth');}
    public function updateReset(Request $request): Response{$data=$request->all();$v=new Validator($data);$v->validate(['token'=>'required|min:20','password'=>'required|strong_password|confirmed']);if($v->fails()){$_SESSION['_errors']=$v->errors();return Response::redirect(route('reset-password',['token'=>(string)($data['token']??'')]));}$id=app('password_resets')->consume((string)$data['token'],(string)$data['password']);if(!$id)return $this->error('This password reset link is invalid or has expired.');$user=app('users')->find($id);if($user){try{app('mail')->send($user['email'],'Your password was changed','action-link',['greeting'=>$user['first_name'],'message'=>'Your password has been changed. If this was not you, contact support immediately.','url'=>route('login'),'action'=>'Review account']);}catch(\Throwable $e){app('logger')->error('Password change notification failed',['message'=>$e->getMessage()]);}app('notifications')->create($id,'password_changed','Password changed','Your password was changed successfully.');}$this->flash('success','Your password has been updated. You can now sign in.');return Response::redirect(route('login'));}
    public function update(Request $request): Response{$user=app('users')->find((int)$_SESSION['user_id']);$data=$request->all();$v=new Validator($data);$v->validate(['current_password'=>'required','password'=>'required|strong_password|confirmed']);if(!$user||$v->fails()||!PasswordHasher::verify((string)$data['current_password'],(string)$user['password_hash']))return $this->error('Current password or new password is invalid.','dashboard.security');app('users')->update((int)$user['id'],['password_hash'=>PasswordHasher::hash((string)$data['password'])]);app('sessions')->revokeOthers((int)$user['id'],(string)$_SESSION['auth_session_hash']);app('security_events')->record((int)$user['id'],'password_changed',$request);app('notifications')->create((int)$user['id'],'password_changed','Other sessions have been signed out.');$this->flash('success','Password updated. Other sessions were signed out.');return Response::redirect(route('dashboard.security'));}
    private function error(string $message,string $routeName='reset-password'): Response{$this->flash('error',$message);return Response::redirect(route($routeName));}
}
