<?php /* One Super Admin control room. */ ?>
<!doctype html><html lang="<?= e(country()->languageCode) ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e(($title ?? '') . ' · Admin') ?></title><link rel="stylesheet" href="<?= e(asset('css/app.css')) ?>"><style nonce="<?= e(app('theme')->nonce()) ?>"><?= app('theme')->css(country()->theme()) ?></style></head>
<body class="app-shell admin">
<aside>
  <div style="padding:4px 8px 18px"><?php require __DIR__.'/../partials/brand.php'; ?><small style="display:block;margin:8px 0 0 48px;color:#8092ad;letter-spacing:.1em">CONTROL ROOM</small></div>
  <a href="<?= e(route('admin.index')) ?>">Overview</a><a href="<?= e(route('admin.users.index')) ?>">Users</a><a href="<?= e(route('admin.countries.index')) ?>">Countries</a><a href="<?= e(route('admin.companies.index')) ?>">Companies</a><a href="<?= e(route('admin.investments')) ?>">Investments</a><a href="<?= e(route('admin.ai-trading')) ?>">AI Trading</a><a href="<?= e(route('admin.sales')) ?>">Sale Requests</a><a href="<?= e(route('admin.deposits')) ?>">Deposits</a><a href="<?= e(route('admin.methods',['kind'=>'deposit'])) ?>">Deposit Methods</a><a href="<?= e(route('admin.methods',['kind'=>'withdrawal'])) ?>">Withdrawal Methods</a><a href="<?= e(route('admin.forms')) ?>">Form Builder</a><a href="<?= e(route('admin.transactions')) ?>">Transactions</a><a href="<?= e(route('admin.kyc')) ?>">KYC</a><a href="<?= e(route('admin.withdrawals')) ?>">Withdrawals</a><a href="<?= e(route('admin.contact-messages')) ?>">Contact Messages</a><a href="<?= e(route('admin.audit')) ?>">Audit Log</a><a href="<?= e(route('admin.settings')) ?>">Settings</a><a href="<?= e(route('home')) ?>">View website</a>
  <form method="post" action="<?= e(route('logout')) ?>" style="padding:0 12px 18px"><?= app('csrf')->input() ?><button class="text-button" type="submit">Sign out</button></form>
</aside>
<section class="workspace"><header><button class="icon-button" data-menu aria-label="Open navigation">☰</button><span>ApexTrades administration</span><a class="avatar" href="<?= e(route('admin.index')) ?>">AD</a></header><?php require __DIR__ . '/../partials/flash.php'; ?><main><?= $content ?></main></section><script src="<?= e(asset('js/app.js')) ?>" defer></script></body></html>
